'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEValueChainPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results by fleet.
        '''</summary>
        Friend ReadOnly Property AGGREGATION_MODE_BYFLEET() As String
            Get
                Return ResourceManager.GetString("AGGREGATION_MODE_BYFLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results by group.
        '''</summary>
        Friend ReadOnly Property AGGREGATION_MODE_BYGROUP() As String
            Get
                Return ResourceManager.GetString("AGGREGATION_MODE_BYGROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unaggregated.
        '''</summary>
        Friend ReadOnly Property AGGREGATION_MODE_FULLMODEL() As String
            Get
                Return ResourceManager.GetString("AGGREGATION_MODE_FULLMODEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer {0}.
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_CONSUMER() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_CONSUMER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distribution {0}.
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_DISTRIBUTION() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_DISTRIBUTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Processing {0}.
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_PROCESSING() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_PROCESSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_PRODUCER() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_PRODUCER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retailer {0}.
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_RETAILER() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_RETAILER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wholesaler {0}.
        '''</summary>
        Friend ReadOnly Property CORE_DEFAULT_WHOLESALER() As String
            Get
                Return ResourceManager.GetString("CORE_DEFAULT_WHOLESALER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ecost_256x256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ecost_256x256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Link already present for group &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property ERROR_LINK_DUPLICATE() As String
            Get
                Return ResourceManager.GetString("ERROR_LINK_DUPLICATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will create a loop which is not allowed.
        '''</summary>
        Friend ReadOnly Property ERROR_LINK_LOOP() As String
            Get
                Return ResourceManager.GetString("ERROR_LINK_LOOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please connect this producer to an Ecopath fleet first.
        '''</summary>
        Friend ReadOnly Property ERROR_LINK_NEEDFLEET() As String
            Get
                Return ResourceManager.GetString("ERROR_LINK_NEEDFLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A link needs a source and a target.
        '''</summary>
        Friend ReadOnly Property ERROR_LINK_NEEDUNITS() As String
            Get
                Return ResourceManager.GetString("ERROR_LINK_NEEDUNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This type of link is not allowed.
        '''</summary>
        Friend ReadOnly Property ERROR_LINK_NOTALLOWED() As String
            Get
                Return ResourceManager.GetString("ERROR_LINK_NOTALLOWED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FormulaEvaluatorHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormulaEvaluatorHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value chain.
        '''</summary>
        Friend ReadOnly Property GENERIC_CAPTION() As String
            Get
                Return ResourceManager.GetString("GENERIC_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value chain plug-in.
        '''</summary>
        Friend ReadOnly Property GENERIC_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("GENERIC_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost.
        '''</summary>
        Friend ReadOnly Property GRAPHDATA_TYPE_COST() As String
            Get
                Return ResourceManager.GetString("GRAPHDATA_TYPE_COST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost and Revenue.
        '''</summary>
        Friend ReadOnly Property GRAPHDATA_TYPE_COSTREVENUE() As String
            Get
                Return ResourceManager.GetString("GRAPHDATA_TYPE_COSTREVENUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dependents.
        '''</summary>
        Friend ReadOnly Property GRAPHDATA_TYPE_DEPENDENTS() As String
            Get
                Return ResourceManager.GetString("GRAPHDATA_TYPE_DEPENDENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jobs.
        '''</summary>
        Friend ReadOnly Property GRAPHDATA_TYPE_JOBS() As String
            Get
                Return ResourceManager.GetString("GRAPHDATA_TYPE_JOBS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Revenue.
        '''</summary>
        Friend ReadOnly Property GRAPHDATA_TYPE_REVENUE() As String
            Get
                Return ResourceManager.GetString("GRAPHDATA_TYPE_REVENUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Categories.
        '''</summary>
        Friend ReadOnly Property HEADER_CATEGORIES() As String
            Get
                Return ResourceManager.GetString("HEADER_CATEGORIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost.
        '''</summary>
        Friend ReadOnly Property HEADER_COST() As String
            Get
                Return ResourceManager.GetString("HEADER_COST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dependents.
        '''</summary>
        Friend ReadOnly Property HEADER_DEPENDENTS() As String
            Get
                Return ResourceManager.GetString("HEADER_DEPENDENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jobs.
        '''</summary>
        Friend ReadOnly Property HEADER_JOBS() As String
            Get
                Return ResourceManager.GetString("HEADER_JOBS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Revenue and cost.
        '''</summary>
        Friend ReadOnly Property HEADER_REV_COST() As String
            Get
                Return ResourceManager.GetString("HEADER_REV_COST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Revenue.
        '''</summary>
        Friend ReadOnly Property HEADER_REVENUE() As String
            Get
                Return ResourceManager.GetString("HEADER_REVENUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_depot_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_depot_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_factory_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_factory_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_fishing_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_fishing_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_meal_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_meal_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_money_bag_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_money_bag_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_shipped_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_shipped_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_shopping_cart_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_shopping_cart_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lenfest_Logo_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lenfest_Logo_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defaults.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_DEFAULTS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_DEFAULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_FLOW() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_PARAMETERS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_PARAMETERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumers.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_CONSUMERS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_CONSUMERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distributors.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_DISTRIBUTORS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_DISTRIBUTORS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Landings.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_LANDINGLINKS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_LANDINGLINKS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Links.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_LINKS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_LINKS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Processors.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_PROCESSORS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_PROCESSORS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Producers.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_PRODUCERS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_PRODUCERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retailers.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_RETAILERS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_RETAILERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wholesalers.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLE_WHOLESALERS() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLE_WHOLESALERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Components.
        '''</summary>
        Friend ReadOnly Property NAVTREE_INPUT_TABLES() As String
            Get
                Return ResourceManager.GetString("NAVTREE_INPUT_TABLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow diagram.
        '''</summary>
        Friend ReadOnly Property NAVTREE_OUTPUT_FLOWDIAGRAM() As String
            Get
                Return ResourceManager.GetString("NAVTREE_OUTPUT_FLOWDIAGRAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run value chain.
        '''</summary>
        Friend ReadOnly Property NAVTREE_OUTPUT_RUN() As String
            Get
                Return ResourceManager.GetString("NAVTREE_OUTPUT_RUN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to arrange the diagram layout?.
        '''</summary>
        Friend ReadOnly Property PROMPT_AUTOLAYOUT() As String
            Get
                Return ResourceManager.GetString("PROMPT_AUTOLAYOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to convert {0} from type &apos;{1}&apos; to type &apos;{2}&apos;?.
        '''</summary>
        Friend ReadOnly Property PROMPT_CONVERT_UNIT() As String
            Get
                Return ResourceManager.GetString("PROMPT_CONVERT_UNIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to delete link &apos;{0}&apos;? This action cannot be undone..
        '''</summary>
        Friend ReadOnly Property PROMPT_DELETELINK() As String
            Get
                Return ResourceManager.GetString("PROMPT_DELETELINK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to delete unit &apos;{0}&apos;? This action cannot be undone..
        '''</summary>
        Friend ReadOnly Property PROMPT_DELETEUNIT() As String
            Get
                Return ResourceManager.GetString("PROMPT_DELETEUNIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVERESULT_DETAIL() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVERESULT_DETAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value chain results failed to save to &apos;{0}&apos;. {1}.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVERESULTS_FAILED() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVERESULTS_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value chain results save to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVERESULTS_SUCCESS() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVERESULTS_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sautxt_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sautxt_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading value chain model, please wait....
        '''</summary>
        Friend ReadOnly Property STATUS_LOADING() As String
            Get
                Return ResourceManager.GetString("STATUS_LOADING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value chain data file &apos;{0}&apos; merged into Ecopath model &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_MERGED() As String
            Get
                Return ResourceManager.GetString("STATUS_MERGED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running value chain equilibrium fleet {0}, effort {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_PROGRESS_EQUILIBIRUM() As String
            Get
                Return ResourceManager.GetString("STATUS_PROGRESS_EQUILIBIRUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running value chain for Ecopath, please wait....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_ECOPATH() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_ECOPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running value chain for Ecosim, please wait....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_ECOSIM() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running value chain Equilibrium search, please wait....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_EQUILIBRIUM() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_EQUILIBRIUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving value chain model, please wait....
        '''</summary>
        Friend ReadOnly Property STATUS_SAVING() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property translate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("translate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_CONSUMER() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_CONSUMER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distribution.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_DISTRIBUTION() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_DISTRIBUTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Processing.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_PROCESSING() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_PROCESSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Producer.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_PRODUCER() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_PRODUCER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retailer.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_RETAILER() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_RETAILER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wholesaler.
        '''</summary>
        Friend ReadOnly Property UNIT_TYPE_WHOLESALER() As String
            Get
                Return ResourceManager.GetString("UNIT_TYPE_WHOLESALER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ValueChain() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ValueChain", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ValueChain_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ValueChain_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
