' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991- 
'    UBC Institute for the Oceans and Fisheries, Vancouver BC, Canada, and
'    Ecopath International Initiative, Barcelona, Spain
' ===============================================================================
'

Imports System.Resources

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

' General Information about an assembly is controlled through the following 
' set of attributes. Change these attribute values to modify the information
' associated with an assembly.

' Review the values of the assembly attributes

<Assembly: AssemblyTitle("EwE MultiSim Plug-in")> 
<Assembly: AssemblyDescription("Routine to read in multiple CSV files altering forcing functions for Ecosim simulations. This routine allows for single or multiple files to be read iteratively and applied to specific forcing functions using either monthly or annual values. User has the ability to select which output files are generated by each Ecosim run")> 
<Assembly: AssemblyCompany("Fisheries and Oceans Canada")> 
<Assembly: AssemblyProduct("EwE MultiSim plug-in")> 
<Assembly: AssemblyCopyright("Copyright © Fisheries and Oceans Canada 2012")> 
<Assembly: AssemblyTrademark("")> 

<Assembly: ComVisible(False)> 

'The following GUID is for the ID of the typelib if this project is exposed to COM
<Assembly: Guid("80c28928-8881-42a5-98e3-6dd099926681")>


'
'      Major Version
'      Minor Version 
'      Build Number
'      Revision
'
' You can specify all the values or you can default the Build and Revision Numbers 
' by using the '*' as shown below:
' <Assembly: AssemblyVersion("1.0.*")> 

<Assembly: AssemblyVersion("6.6.15495.0")>
<Assembly: AssemblyFileVersion("6.6.15495.0")>
