'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMultiSimPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim example CSV input file could not be written to &apos;{0}&apos;. {1}.
        '''</summary>
        Friend ReadOnly Property EXAMPLE_EXPORT_FAILED() As String
            Get
                Return ResourceManager.GetString("EXAMPLE_EXPORT_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim example CSV input file written to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property EXAMPLE_EXPORT_SUCCESS() As String
            Get
                Return ResourceManager.GetString("EXAMPLE_EXPORT_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim example CSV input file written to &apos;{0}&apos;, but some problems were encountered for scenario {1}..
        '''</summary>
        Friend ReadOnly Property EXAMPLE_EXPORT_WARNING() As String
            Get
                Return ResourceManager.GetString("EXAMPLE_EXPORT_WARNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Routine to read in multiple CSV files altering forcing functions for Ecosim simulations. This routine allows for single or multiple files to be read iteratively and applied to specific forcing functions using either monthly or annual values. Users have the ability to select which output files are generated by each Ecosim run. Development of this plug-in was funded by Fisheries and Oceans Canada&apos;s Aquatic Climate Change Adaptation Services Program (ACCASP)..
        '''</summary>
        Friend ReadOnly Property GENERIC_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("GENERIC_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim.
        '''</summary>
        Friend ReadOnly Property GENERIC_NAME() As String
            Get
                Return ResourceManager.GetString("GENERIC_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_canada_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_canada_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ÖCengsvart_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ÖCengsvart_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim did not complete successfully, see &apos;{0}&apos; for details.
        '''</summary>
        Friend ReadOnly Property STATUS_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initializing....
        '''</summary>
        Friend ReadOnly Property STATUS_INITIALIZING() As String
            Get
                Return ResourceManager.GetString("STATUS_INITIALIZING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &apos;{0}&apos; loading....
        '''</summary>
        Friend ReadOnly Property STATUS_LOADING() As String
            Get
                Return ResourceManager.GetString("STATUS_LOADING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring data....
        '''</summary>
        Friend ReadOnly Property STATUS_RESTORING() As String
            Get
                Return ResourceManager.GetString("STATUS_RESTORING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running CSV file &apos;{0}&apos;....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving results for CSV file &apos;{0}&apos;....
        '''</summary>
        Friend ReadOnly Property STATUS_SAVING() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim completed successfully, see &apos;{0}&apos; for details.
        '''</summary>
        Friend ReadOnly Property STATUS_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV {0} refers to unknown function &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_FN_MISSING() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_FN_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reading CSV file {0}.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_READ() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_READ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: something went wrong while reading CSV file {0}: {1}.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_READ_ERROR() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_READ_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: unable to find CSV file {0}.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_READ_MISSING() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_READ_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV file {0} uses both effort and fishing mortality shapes, which could lead to unpredictable results in Ecosim.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_SUMMARY_EFFORT_FMORT_WARNING() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_SUMMARY_EFFORT_FMORT_WARNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSF file {0} cannot vary both individual fleets and all fleets; the data for all fleets will take precedence. Either remove the individual fleets or remove the all fleets data.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_SUMMARY_FLEET_ERROR() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_SUMMARY_FLEET_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV file {0} refers to {1} unknown function(s).
        '''</summary>
        Friend ReadOnly Property VAL_CSV_SUMMARY_MISSING() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_SUMMARY_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All functions found in Ecosim.
        '''</summary>
        Friend ReadOnly Property VAL_CSV_SUMMARY_OK() As String
            Get
                Return ResourceManager.GetString("VAL_CSV_SUMMARY_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are multiple functions with the name &apos;{0}&apos; in Ecosim. Multi-sim cannot run until this has been resolved..
        '''</summary>
        Friend ReadOnly Property VALIDATION_DETAIL_FN_DUPLICATE() As String
            Get
                Return ResourceManager.GetString("VALIDATION_DETAIL_FN_DUPLICATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim cannot run, there are errors in your setup that you will need to resolve. Please check the status panel or &apos;{0}&apos; for details.
        '''</summary>
        Friend ReadOnly Property VALIDATION_RESULT_FAILED() As String
            Get
                Return ResourceManager.GetString("VALIDATION_RESULT_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim is ready to run; Ecosim scenario {0} and all selected CSV files are in order.
        '''</summary>
        Friend ReadOnly Property VALIDATION_RESULT_SUCCESS() As String
            Get
                Return ResourceManager.GetString("VALIDATION_RESULT_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-sim could run but there are problems in your setup that you may want to resolve first. Please check the status panel or &apos;{0}&apos; for details.
        '''</summary>
        Friend ReadOnly Property VALIDATION_RESULT_WARNING() As String
            Get
                Return ResourceManager.GetString("VALIDATION_RESULT_WARNING", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
