'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("My.Computer.FileSystem.SpecialDirectories.MyDocuments"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property LastSelectedDirectory() As String
        Get
            Return CType(Me("LastSelectedDirectory"),String)
        End Get
        Set
            Me("LastSelectedDirectory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfAnyType xmlns:xsi=""http://www.w3"& _ 
        ".org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
        "anyType />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfAnyType>"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property MdbRecentlyUsedList() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("MdbRecentlyUsedList"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("MdbRecentlyUsedList") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property SettingLoaded() As Boolean
        Get
            Return CType(Me("SettingLoaded"),Boolean)
        End Get
        Set
            Me("SettingLoaded") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0, 0, 244"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorComputedValuesText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorComputedValuesText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorComputedValuesText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("OrangeRed"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorErrorBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorErrorBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorErrorBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DarkGoldenrod"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorFailedValidationText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorFailedValidationText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorFailedValidationText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Red"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorFailedResultText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorFailedResultText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorFailedResultText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorDefaultText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorDefaultText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorDefaultText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorNameText() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorNameText"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorNameText") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorRemarksBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorRemarksBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorRemarksBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("255, 254, 225"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorSumBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorSumBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorSumBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("231, 235, 250"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorReadOnlyBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorReadOnlyBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorReadOnlyBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("176, 233, 173"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorCheckedBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorCheckedBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorCheckedBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MediumPurple"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorMissingParamBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorMissingParamBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorMissingParamBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorImageBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorImageBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorImageBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorPlotsBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorPlotsBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorPlotsBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ControlDark"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorMapBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorMapBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorMapBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorDefaultBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorDefaultBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorDefaultBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("232, 232, 232"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property ColorNameBackground() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorNameBackground"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorNameBackground") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property DisabledPlugins() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("DisabledPlugins"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("DisabledPlugins") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FormSettings() As Global.System.Xml.XmlDocument
        Get
            Return CType(Me("FormSettings"),Global.System.Xml.XmlDocument)
        End Get
        Set
            Me("FormSettings") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
    Public Property StatusMaxMessages() As Integer
        Get
            Return CType(Me("StatusMaxMessages"),Integer)
        End Get
        Set
            Me("StatusMaxMessages") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontTitle() As String
        Get
            Return CType(Me("FontTitle"),String)
        End Get
        Set
            Me("FontTitle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontLegend() As String
        Get
            Return CType(Me("FontLegend"),String)
        End Get
        Set
            Me("FontLegend") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontSubtitle() As String
        Get
            Return CType(Me("FontSubtitle"),String)
        End Get
        Set
            Me("FontSubtitle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontScale() As String
        Get
            Return CType(Me("FontScale"),String)
        End Get
        Set
            Me("FontScale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontValue() As String
        Get
            Return CType(Me("FontValue"),String)
        End Get
        Set
            Me("FontValue") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("48")>  _
    Public Property ThumbnailSize() As Integer
        Get
            Return CType(Me("ThumbnailSize"),Integer)
        End Get
        Set
            Me("ThumbnailSize") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-2")>  _
    Public Property ShowLegends() As Integer
        Get
            Return CType(Me("ShowLegends"),Integer)
        End Get
        Set
            Me("ShowLegends") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseTransparentBackgrounds() As Boolean
        Get
            Return CType(Me("UseTransparentBackgrounds"),Boolean)
        End Get
        Set
            Me("UseTransparentBackgrounds") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("16"),  _
     Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
    Public Property MdbRecentlyUsedCount() As Integer
        Get
            Return CType(Me("MdbRecentlyUsedCount"),Integer)
        End Get
        Set
            Me("MdbRecentlyUsedCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property SuppressedOverwritePrompts() As String
        Get
            Return CType(Me("SuppressedOverwritePrompts"),String)
        End Get
        Set
            Me("SuppressedOverwritePrompts") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property PresentationModeHideModelBar() As Boolean
        Get
            Return CType(Me("PresentationModeHideModelBar"),Boolean)
        End Get
        Set
            Me("PresentationModeHideModelBar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PresentationModeHideMainMenu() As Boolean
        Get
            Return CType(Me("PresentationModeHideMainMenu"),Boolean)
        End Get
        Set
            Me("PresentationModeHideMainMenu") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property PresentationModeHideStatusBar() As Boolean
        Get
            Return CType(Me("PresentationModeHideStatusBar"),Boolean)
        End Get
        Set
            Me("PresentationModeHideStatusBar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PresentationModeCollapseNavPanel() As Boolean
        Get
            Return CType(Me("PresentationModeCollapseNavPanel"),Boolean)
        End Get
        Set
            Me("PresentationModeCollapseNavPanel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property StatusShowTime() As Boolean
        Get
            Return CType(Me("StatusShowTime"),Boolean)
        End Get
        Set
            Me("StatusShowTime") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("{MyDocuments}\EwE backup\{ModelFile}_{Date}-{Time}.{ModelExt}")>  _
    Public Property BackupFileMask() As String
        Get
            Return CType(Me("BackupFileMask"),String)
        End Get
        Set
            Me("BackupFileMask") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("{MyDocuments}\EwE output\{ModelFile}")>  _
    Public Property OutputPathMask() As String
        Get
            Return CType(Me("OutputPathMask"),String)
        End Get
        Set
            Me("OutputPathMask") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowHostInfo() As Boolean
        Get
            Return CType(Me("ShowHostInfo"),Boolean)
        End Get
        Set
            Me("ShowHostInfo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property MapLayerRefFile() As String
        Get
            Return CType(Me("MapLayerRefFile"),String)
        End Get
        Set
            Me("MapLayerRefFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-180")>  _
    Public Property MapLayerRefLonMin() As Single
        Get
            Return CType(Me("MapLayerRefLonMin"),Single)
        End Get
        Set
            Me("MapLayerRefLonMin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
    Public Property MapLayerRefLonMax() As Single
        Get
            Return CType(Me("MapLayerRefLonMax"),Single)
        End Get
        Set
            Me("MapLayerRefLonMax") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-90")>  _
    Public Property MapLayerRefLatMin() As Single
        Get
            Return CType(Me("MapLayerRefLatMin"),Single)
        End Get
        Set
            Me("MapLayerRefLatMin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
    Public Property MapLayerRefLatMax() As Single
        Get
            Return CType(Me("MapLayerRefLatMax"),Single)
        End Get
        Set
            Me("MapLayerRefLatMax") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LogVerboseLevel() As Integer
        Get
            Return CType(Me("LogVerboseLevel"),Integer)
        End Get
        Set
            Me("LogVerboseLevel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Author() As String
        Get
            Return CType(Me("Author"),String)
        End Get
        Set
            Me("Author") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Contact() As String
        Get
            Return CType(Me("Contact"),String)
        End Get
        Set
            Me("Contact") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LimeGreen")>  _
    Public Property ColorPrey() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorPrey"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorPrey") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("IndianRed")>  _
    Public Property ColorPredator() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorPredator"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorPredator") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Orange")>  _
    Public Property ColorPedigree() As Global.System.Drawing.Color
        Get
            Return CType(Me("ColorPedigree"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ColorPedigree") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SelectionLinkThroughFishing() As Boolean
        Get
            Return CType(Me("SelectionLinkThroughFishing"),Boolean)
        End Get
        Set
            Me("SelectionLinkThroughFishing") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AutosaveHeaders() As Boolean
        Get
            Return CType(Me("AutosaveHeaders"),Boolean)
        End Get
        Set
            Me("AutosaveHeaders") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property AutosaveResults() As Global.System.Xml.XmlDocument
        Get
            Return CType(Me("AutosaveResults"),Global.System.Xml.XmlDocument)
        End Get
        Set
            Me("AutosaveResults") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
    Public Property OutputDPI() As Integer
        Get
            Return CType(Me("OutputDPI"),Integer)
        End Get
        Set
            Me("OutputDPI") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowPedigree() As Boolean
        Get
            Return CType(Me("ShowPedigree"),Boolean)
        End Get
        Set
            Me("ShowPedigree") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property SpatialTemporalConfigFile() As String
        Get
            Return CType(Me("SpatialTemporalConfigFile"),String)
        End Get
        Set
            Me("SpatialTemporalConfigFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FontFlowDiagram() As String
        Get
            Return CType(Me("FontFlowDiagram"),String)
        End Get
        Set
            Me("FontFlowDiagram") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MapShowExcludedCells() As Boolean
        Get
            Return CType(Me("MapShowExcludedCells"),Boolean)
        End Get
        Set
            Me("MapShowExcludedCells") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfAnyType xmlns:xsi=""http://www.w3"& _ 
        ".org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
        "anyType />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfAnyType>")>  _
    Public Property SpatialTempConfigurations() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("SpatialTempConfigurations"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("SpatialTempConfigurations") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowSplash() As Boolean
        Get
            Return CType(Me("ShowSplash"),Boolean)
        End Get
        Set
            Me("ShowSplash") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ShowExtraVariableInfo() As Boolean
        Get
            Return CType(Me("ShowExtraVariableInfo"),Boolean)
        End Get
        Set
            Me("ShowExtraVariableInfo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property ColorCustom() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("ColorCustom"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("ColorCustom") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property CountryNames() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("CountryNames"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("CountryNames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property EcosystemTypes() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("EcosystemTypes"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("EcosystemTypes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property LastWSDLUpdate() As Date
        Get
            Return CType(Me("LastWSDLUpdate"),Date)
        End Get
        Set
            Me("LastWSDLUpdate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseExternalBrowser() As Boolean
        Get
            Return CType(Me("UseExternalBrowser"),Boolean)
        End Get
        Set
            Me("UseExternalBrowser") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property StatusShowVariableValidations() As Boolean
        Get
            Return CType(Me("StatusShowVariableValidations"),Boolean)
        End Get
        Set
            Me("StatusShowVariableValidations") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseHabitatAreaCorrection() As Boolean
        Get
            Return CType(Me("UseHabitatAreaCorrection"),Boolean)
        End Get
        Set
            Me("UseHabitatAreaCorrection") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MapShowMPAs() As Boolean
        Get
            Return CType(Me("MapShowMPAs"),Boolean)
        End Get
        Set
            Me("MapShowMPAs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MapShowLabels() As Boolean
        Get
            Return CType(Me("MapShowLabels"),Boolean)
        End Get
        Set
            Me("MapShowLabels") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MapShowLabelDate() As Boolean
        Get
            Return CType(Me("MapShowLabelDate"),Boolean)
        End Get
        Set
            Me("MapShowLabelDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MapShowLabelInvertedColor() As Boolean
        Get
            Return CType(Me("MapShowLabelInvertedColor"),Boolean)
        End Get
        Set
            Me("MapShowLabelInvertedColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property MapLabelPosHorz() As Integer
        Get
            Return CType(Me("MapLabelPosHorz"),Integer)
        End Get
        Set
            Me("MapLabelPosHorz") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property MapLabelPosVert() As Integer
        Get
            Return CType(Me("MapLabelPosVert"),Integer)
        End Get
        Set
            Me("MapLabelPosVert") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property StatusSortNewestFirst() As Boolean
        Get
            Return CType(Me("StatusSortNewestFirst"),Boolean)
        End Get
        Set
            Me("StatusSortNewestFirst") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SpatialTempAllowIndexing() As Boolean
        Get
            Return CType(Me("SpatialTempAllowIndexing"),Boolean)
        End Get
        Set
            Me("SpatialTempAllowIndexing") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property StatusAutoPopop() As Boolean
        Get
            Return CType(Me("StatusAutoPopop"),Boolean)
        End Get
        Set
            Me("StatusAutoPopop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UseEcospaceSpinup() As Boolean
        Get
            Return CType(Me("UseEcospaceSpinup"),Boolean)
        End Get
        Set
            Me("UseEcospaceSpinup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SelectionLinkThroughPredation() As Boolean
        Get
            Return CType(Me("SelectionLinkThroughPredation"),Boolean)
        End Get
        Set
            Me("SelectionLinkThroughPredation") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ShowEffortMortalityInRunSim() As Boolean
        Get
            Return CType(Me("ShowEffortMortalityInRunSim"),Boolean)
        End Get
        Set
            Me("ShowEffortMortalityInRunSim") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScientificInterface.Settings
            Get
                Return Global.ScientificInterface.Settings.Default
            End Get
        End Property
    End Module
End Namespace
