'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwETransectExtractionPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass along transect.
        '''</summary>
        Friend ReadOnly Property CAPTION_BIOMASS() As String
            Get
                Return ResourceManager.GetString("CAPTION_BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch along transect.
        '''</summary>
        Friend ReadOnly Property CAPTION_CATCH() As String
            Get
                Return ResourceManager.GetString("CAPTION_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Depth along transect.
        '''</summary>
        Friend ReadOnly Property CAPTION_DEPTH() As String
            Get
                Return ResourceManager.GetString("CAPTION_DEPTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transects.
        '''</summary>
        Friend ReadOnly Property CAPTION_IN() As String
            Get
                Return ResourceManager.GetString("CAPTION_IN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPAs along transect.
        '''</summary>
        Friend ReadOnly Property CAPTION_MPA() As String
            Get
                Return ResourceManager.GetString("CAPTION_MPA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transect summary.
        '''</summary>
        Friend ReadOnly Property CAPTION_OUT() As String
            Get
                Return ResourceManager.GetString("CAPTION_OUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0}, {1}).
        '''</summary>
        Friend ReadOnly Property GENERIC_LABEL_POINT() As String
            Get
                Return ResourceManager.GetString("GENERIC_LABEL_POINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cell.
        '''</summary>
        Friend ReadOnly Property LABEL_CELL() As String
            Get
                Return ResourceManager.GetString("LABEL_CELL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no summary yet).
        '''</summary>
        Friend ReadOnly Property LABEL_NODATA() As String
            Get
                Return ResourceManager.GetString("LABEL_NODATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timestep {0}/{1}.
        '''</summary>
        Friend ReadOnly Property LABEL_TIMESTEP() As String
            Get
                Return ResourceManager.GetString("LABEL_TIMESTEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Num. intersecting MPAs.
        '''</summary>
        Friend ReadOnly Property UNIT_MPACOUNT() As String
            Get
                Return ResourceManager.GetString("UNIT_MPACOUNT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
