'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEResultsExtractor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All options.
        '''</summary>
        Friend ReadOnly Property ALL_OPTIONS() As String
            Get
                Return ResourceManager.GetString("ALL_OPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assimilation(t/hm^2/year).
        '''</summary>
        Friend ReadOnly Property ASSIMILATION_UNITS() As String
            Get
                Return ResourceManager.GetString("ASSIMILATION_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attach All.
        '''</summary>
        Friend ReadOnly Property ATTACH_ALL() As String
            Get
                Return ResourceManager.GetString("ATTACH_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basic estimates.
        '''</summary>
        Friend ReadOnly Property BASIC_ESTIMATES() As String
            Get
                Return ResourceManager.GetString("BASIC_ESTIMATES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass.
        '''</summary>
        Friend ReadOnly Property BIOMASS() As String
            Get
                Return ResourceManager.GetString("BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biom. Accumul.
        '''</summary>
        Friend ReadOnly Property BIOMASS_ACCUM() As String
            Get
                Return ResourceManager.GetString("BIOMASS_ACCUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biom. Acc. Rate.
        '''</summary>
        Friend ReadOnly Property BIOMASS_ACCUM_RATE() As String
            Get
                Return ResourceManager.GetString("BIOMASS_ACCUM_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass in habitat area ({0}/{1}).
        '''</summary>
        Friend ReadOnly Property BIOMASS_AREA_UNITS() As String
            Get
                Return ResourceManager.GetString("BIOMASS_AREA_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass(t/km^2).
        '''</summary>
        Friend ReadOnly Property BIOMASS_UNITS() As String
            Get
                Return ResourceManager.GetString("BIOMASS_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BiomassInteg.
        '''</summary>
        Friend ReadOnly Property BIOMASSINTEG() As String
            Get
                Return ResourceManager.GetString("BIOMASSINTEG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass integrated.
        '''</summary>
        Friend ReadOnly Property BIOMASSINTEGRATED() As String
            Get
                Return ResourceManager.GetString("BIOMASSINTEGRATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property CANCEL() As String
            Get
                Return ResourceManager.GetString("CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch.
        '''</summary>
        Friend ReadOnly Property CATCH_() As String
            Get
                Return ResourceManager.GetString("CATCH_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch per fleet.
        '''</summary>
        Friend ReadOnly Property CATCH_PER_FLEET() As String
            Get
                Return ResourceManager.GetString("CATCH_PER_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CatchPerFleetPerPrey.
        '''</summary>
        Friend ReadOnly Property CATCH_PER_FLEETGROUP() As String
            Get
                Return ResourceManager.GetString("CATCH_PER_FLEETGROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch Value.
        '''</summary>
        Friend ReadOnly Property CATCH_VALUE() As String
            Get
                Return ResourceManager.GetString("CATCH_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Selection.
        '''</summary>
        Friend ReadOnly Property CHANGE_SELECTION() As String
            Get
                Return ResourceManager.GetString("CHANGE_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumpt.
        '''</summary>
        Friend ReadOnly Property CONSUMPT() As String
            Get
                Return ResourceManager.GetString("CONSUMPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption.
        '''</summary>
        Friend ReadOnly Property CONSUMPTION() As String
            Get
                Return ResourceManager.GetString("CONSUMPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption/biomass(/yr).
        '''</summary>
        Friend ReadOnly Property CONSUMPTION_BIOMASS_UNITS() As String
            Get
                Return ResourceManager.GetString("CONSUMPTION_BIOMASS_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data retrieval in progress....
        '''</summary>
        Friend ReadOnly Property DATA_RETRIEVAL() As String
            Get
                Return ResourceManager.GetString("DATA_RETRIEVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detach All.
        '''</summary>
        Friend ReadOnly Property DETACH_ALL() As String
            Get
                Return ResourceManager.GetString("DETACH_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnostics.
        '''</summary>
        Friend ReadOnly Property DIAGNOSTICS() As String
            Get
                Return ResourceManager.GetString("DIAGNOSTICS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diet Proportions.
        '''</summary>
        Friend ReadOnly Property DIET_PROPS() As String
            Get
                Return ResourceManager.GetString("DIET_PROPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DietOf.
        '''</summary>
        Friend ReadOnly Property DIETOF() As String
            Get
                Return ResourceManager.GetString("DIETOF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DiscardsPerFleetPerPrey.
        '''</summary>
        Friend ReadOnly Property DISCARDS_PER_FLEETPREY() As String
            Get
                Return ResourceManager.GetString("DISCARDS_PER_FLEETPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .CSV.
        '''</summary>
        Friend ReadOnly Property DOTCSV() As String
            Get
                Return ResourceManager.GetString("DOTCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecotrophic efficiency.
        '''</summary>
        Friend ReadOnly Property ECOTROPHIC_EFFICIENCY() As String
            Get
                Return ResourceManager.GetString("ECOTROPHIC_EFFICIENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effort.
        '''</summary>
        Friend ReadOnly Property EFFORT() As String
            Get
                Return ResourceManager.GetString("EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Electivity.
        '''</summary>
        Friend ReadOnly Property ELECTIVITY() As String
            Get
                Return ResourceManager.GetString("ELECTIVITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excel.
        '''</summary>
        Friend ReadOnly Property EXCEL() As String
            Get
                Return ResourceManager.GetString("EXCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mort. rate.
        '''</summary>
        Friend ReadOnly Property FISH_MORT_RATE() As String
            Get
                Return ResourceManager.GetString("FISH_MORT_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mort./Total mort.
        '''</summary>
        Friend ReadOnly Property FISH_MORT_TOTAL_MORT() As String
            Get
                Return ResourceManager.GetString("FISH_MORT_TOTAL_MORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fisheries.
        '''</summary>
        Friend ReadOnly Property FISHERIES() As String
            Get
                Return ResourceManager.GetString("FISHERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FisheriesGroups.
        '''</summary>
        Friend ReadOnly Property FISHERIESGROUPS() As String
            Get
                Return ResourceManager.GetString("FISHERIESGROUPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FishingEffort.
        '''</summary>
        Friend ReadOnly Property FISHING_EFFORT() As String
            Get
                Return ResourceManager.GetString("FISHING_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing quantities.
        '''</summary>
        Friend ReadOnly Property FISHING_QUANT() As String
            Get
                Return ResourceManager.GetString("FISHING_QUANT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing values.
        '''</summary>
        Friend ReadOnly Property FISHING_VALUES() As String
            Get
                Return ResourceManager.GetString("FISHING_VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mortality.
        '''</summary>
        Friend ReadOnly Property FISHMORT() As String
            Get
                Return ResourceManager.GetString("FISHMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FishMortAllFleet.
        '''</summary>
        Friend ReadOnly Property FISHMORT_ALLFLEET() As String
            Get
                Return ResourceManager.GetString("FISHMORT_ALLFLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mortality (Fleet to Prey).
        '''</summary>
        Friend ReadOnly Property FISHMORT_FLEET2PREY() As String
            Get
                Return ResourceManager.GetString("FISHMORT_FLEET2PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FishMortPerFleet.
        '''</summary>
        Friend ReadOnly Property FISHMORT_PER_FLEET() As String
            Get
                Return ResourceManager.GetString("FISHMORT_PER_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fitting statistics.
        '''</summary>
        Friend ReadOnly Property FITTING_STATS() As String
            Get
                Return ResourceManager.GetString("FITTING_STATS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet.
        '''</summary>
        Friend ReadOnly Property FLEET() As String
            Get
                Return ResourceManager.GetString("FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet only.
        '''</summary>
        Friend ReadOnly Property FLEET_ONLY() As String
            Get
                Return ResourceManager.GetString("FLEET_ONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet selection.
        '''</summary>
        Friend ReadOnly Property FLEET_SELECTION() As String
            Get
                Return ResourceManager.GetString("FLEET_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet to many prey.
        '''</summary>
        Friend ReadOnly Property FLEET2_MANYPREY() As String
            Get
                Return ResourceManager.GetString("FLEET2_MANYPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleet to prey selection.
        '''</summary>
        Friend ReadOnly Property FLEET2PREY_SELECTION() As String
            Get
                Return ResourceManager.GetString("FLEET2PREY_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleets with attached prey.
        '''</summary>
        Friend ReadOnly Property FLEETS_ATTACHED_PREY() As String
            Get
                Return ResourceManager.GetString("FLEETS_ATTACHED_PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fleets only.
        '''</summary>
        Friend ReadOnly Property FLEETS_ONLY() As String
            Get
                Return ResourceManager.GetString("FLEETS_ONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow to det..
        '''</summary>
        Friend ReadOnly Property FLOW_DETRITUS() As String
            Get
                Return ResourceManager.GetString("FLOW_DETRITUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select which groups for which you would like to extract results.
        '''</summary>
        Friend ReadOnly Property FORMNAME_SELECTGROUPS() As String
            Get
                Return ResourceManager.GetString("FORMNAME_SELECTGROUPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FunctGroup.
        '''</summary>
        Friend ReadOnly Property FUNC_GROUP() As String
            Get
                Return ResourceManager.GetString("FUNC_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Functional group selection.
        '''</summary>
        Friend ReadOnly Property FUNCT_GROUP_SELECTION() As String
            Get
                Return ResourceManager.GetString("FUNCT_GROUP_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Functional groups only.
        '''</summary>
        Friend ReadOnly Property FUNCT_GROUPS_ONLY() As String
            Get
                Return ResourceManager.GetString("FUNCT_GROUPS_ONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FunctionalGroups.
        '''</summary>
        Friend ReadOnly Property FUNCTIONALGROUPS() As String
            Get
                Return ResourceManager.GetString("FUNCTIONALGROUPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} {1}.csv.
        '''</summary>
        Friend ReadOnly Property GENERIC_CSV_FILE() As String
            Get
                Return ResourceManager.GetString("GENERIC_CSV_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Result Extractor has saved the following file(s) to &apos;{0}&apos;:.
        '''</summary>
        Friend ReadOnly Property GENERIC_SAVE() As String
            Get
                Return ResourceManager.GetString("GENERIC_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results saved to &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property GENERIC_SAVE_CSV() As String
            Get
                Return ResourceManager.GetString("GENERIC_SAVE_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results added to workbook &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property GENERIC_SAVE_EXCEL() As String
            Get
                Return ResourceManager.GetString("GENERIC_SAVE_EXCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Result Extractor failed to save results to {0}. A system error occurred. {1}.
        '''</summary>
        Friend ReadOnly Property GENERIC_SAVE_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("GENERIC_SAVE_EXCEPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group.
        '''</summary>
        Friend ReadOnly Property GROUP() As String
            Get
                Return ResourceManager.GetString("GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group Name.
        '''</summary>
        Friend ReadOnly Property GROUP_NAME() As String
            Get
                Return ResourceManager.GetString("GROUP_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Habitat area(fraction).
        '''</summary>
        Friend ReadOnly Property HABITAT_AREA_UNITS() As String
            Get
                Return ResourceManager.GetString("HABITAT_AREA_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend ReadOnly Property IMPORT() As String
            Get
                Return ResourceManager.GetString("IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index.
        '''</summary>
        Friend ReadOnly Property INDEX() As String
            Get
                Return ResourceManager.GetString("INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicators.
        '''</summary>
        Friend ReadOnly Property INDICATORS() As String
            Get
                Return ResourceManager.GetString("INDICATORS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial consumption.
        '''</summary>
        Friend ReadOnly Property INIT_CONSUMPTION() As String
            Get
                Return ResourceManager.GetString("INIT_CONSUMPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial fishing mortality.
        '''</summary>
        Friend ReadOnly Property INIT_FISH_MORT() As String
            Get
                Return ResourceManager.GetString("INIT_FISH_MORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitMortCoeffs.
        '''</summary>
        Friend ReadOnly Property INIT_MORT_COEFFS() As String
            Get
                Return ResourceManager.GetString("INIT_MORT_COEFFS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial predation mortality.
        '''</summary>
        Friend ReadOnly Property INIT_PRED_MORT() As String
            Get
                Return ResourceManager.GetString("INIT_PRED_MORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitConsumption.
        '''</summary>
        Friend ReadOnly Property INITCONSUMPTION() As String
            Get
                Return ResourceManager.GetString("INITCONSUMPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitFishingMortality.
        '''</summary>
        Friend ReadOnly Property INITFISHMORT() As String
            Get
                Return ResourceManager.GetString("INITFISHMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitFishingQuantities.
        '''</summary>
        Friend ReadOnly Property INITFISHQUANTS() As String
            Get
                Return ResourceManager.GetString("INITFISHQUANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitFishingValues.
        '''</summary>
        Friend ReadOnly Property INITFISHVALUES() As String
            Get
                Return ResourceManager.GetString("INITFISHVALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InitPredMort.
        '''</summary>
        Friend ReadOnly Property INITPREDMORT() As String
            Get
                Return ResourceManager.GetString("INITPREDMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Selection.
        '''</summary>
        Friend ReadOnly Property INVALID_SELECTION() As String
            Get
                Return ResourceManager.GetString("INVALID_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Key indices.
        '''</summary>
        Friend ReadOnly Property KEY_INDICES() As String
            Get
                Return ResourceManager.GetString("KEY_INDICES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LandingsPerFleetPerPrey.
        '''</summary>
        Friend ReadOnly Property LANDINGS_PER_FLEETPREY() As String
            Get
                Return ResourceManager.GetString("LANDINGS_PER_FLEETPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mortality coefficients.
        '''</summary>
        Friend ReadOnly Property MORT_COEFFS() As String
            Get
                Return ResourceManager.GetString("MORT_COEFFS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your entry on the previous form was invalid.
        '''Would you like to retry your entry or cancel the
        '''process?.
        '''</summary>
        Friend ReadOnly Property MSG_PREV_FORM_INVALID() As String
            Get
                Return ResourceManager.GetString("MSG_PREV_FORM_INVALID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Efficiency.
        '''</summary>
        Friend ReadOnly Property NET_EFFICIENCY() As String
            Get
                Return ResourceManager.GetString("NET_EFFICIENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Migration.
        '''</summary>
        Friend ReadOnly Property NET_MIGRATION() As String
            Get
                Return ResourceManager.GetString("NET_MIGRATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Migration Rate.
        '''</summary>
        Friend ReadOnly Property NET_MIGRATION_RATE() As String
            Get
                Return ResourceManager.GetString("NET_MIGRATION_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non-market value.
        '''</summary>
        Friend ReadOnly Property NONMARKET_VALUE() As String
            Get
                Return ResourceManager.GetString("NONMARKET_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Omnivory Index.
        '''</summary>
        Friend ReadOnly Property OMNIVORY_INDEX() As String
            Get
                Return ResourceManager.GetString("OMNIVORY_INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other mort. rate.
        '''</summary>
        Friend ReadOnly Property OTHER_MORT_RATE() As String
            Get
                Return ResourceManager.GetString("OTHER_MORT_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OverlapPred.
        '''</summary>
        Friend ReadOnly Property OVERLAPPRED() As String
            Get
                Return ResourceManager.GetString("OVERLAPPRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OverlapPrey.
        '''</summary>
        Friend ReadOnly Property OVERLAPPREY() As String
            Get
                Return ResourceManager.GetString("OVERLAPPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parent only.
        '''</summary>
        Friend ReadOnly Property PARENT_ONLY() As String
            Get
                Return ResourceManager.GetString("PARENT_ONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plug-in to aid in extracting results, parameter values and data from EwE.
        '''</summary>
        Friend ReadOnly Property PLUGIN_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("PLUGIN_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results Extractor.
        '''</summary>
        Friend ReadOnly Property PLUGIN_NAME() As String
            Get
                Return ResourceManager.GetString("PLUGIN_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predat. mort. rate.
        '''</summary>
        Friend ReadOnly Property PRED_MORT_RATE() As String
            Get
                Return ResourceManager.GetString("PRED_MORT_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pedator overlap.
        '''</summary>
        Friend ReadOnly Property PRED_OVERLAP() As String
            Get
                Return ResourceManager.GetString("PRED_OVERLAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predator to many prey.
        '''</summary>
        Friend ReadOnly Property PRED2_MANYPREY() As String
            Get
                Return ResourceManager.GetString("PRED2_MANYPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predator to prey selection.
        '''</summary>
        Friend ReadOnly Property PRED2PREY_SELECTION() As String
            Get
                Return ResourceManager.GetString("PRED2PREY_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predation mortality
        ''' per predator.
        '''</summary>
        Friend ReadOnly Property PREDATION_PER_PRED() As String
            Get
                Return ResourceManager.GetString("PREDATION_PER_PRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predation mortality.
        '''</summary>
        Friend ReadOnly Property PREDATIONMORT() As String
            Get
                Return ResourceManager.GetString("PREDATIONMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predator.
        '''</summary>
        Friend ReadOnly Property PREDATOR() As String
            Get
                Return ResourceManager.GetString("PREDATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PredMort.
        '''</summary>
        Friend ReadOnly Property PREDMORT() As String
            Get
                Return ResourceManager.GetString("PREDMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PredMortEachPred.
        '''</summary>
        Friend ReadOnly Property PREDMORT_EACH_PRED() As String
            Get
                Return ResourceManager.GetString("PREDMORT_EACH_PRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predators with attached prey.
        '''</summary>
        Friend ReadOnly Property PREDS_ATTACHED_PREY() As String
            Get
                Return ResourceManager.GetString("PREDS_ATTACHED_PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prey.
        '''</summary>
        Friend ReadOnly Property PREY() As String
            Get
                Return ResourceManager.GetString("PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prey overlap.
        '''</summary>
        Friend ReadOnly Property PREY_OVERLAP() As String
            Get
                Return ResourceManager.GetString("PREY_OVERLAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prey to many predators.
        '''</summary>
        Friend ReadOnly Property PREY2_MANYPRED() As String
            Get
                Return ResourceManager.GetString("PREY2_MANYPRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prey to predator selection.
        '''</summary>
        Friend ReadOnly Property PREY2PRED_SELECTION() As String
            Get
                Return ResourceManager.GetString("PREY2PRED_SELECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prey with attached predators.
        '''</summary>
        Friend ReadOnly Property PREYS_ATTACHED_PRED() As String
            Get
                Return ResourceManager.GetString("PREYS_ATTACHED_PRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prod/Biom or Z.
        '''</summary>
        Friend ReadOnly Property PROD_BIOMASS_Z() As String
            Get
                Return ResourceManager.GetString("PROD_BIOMASS_Z", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Production/biomass(/yr).
        '''</summary>
        Friend ReadOnly Property PRODUCTION_BIOMASS_UNITS() As String
            Get
                Return ResourceManager.GetString("PRODUCTION_BIOMASS_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Production/Consumption.
        '''</summary>
        Friend ReadOnly Property PRODUCTION_CONSUMPTION() As String
            Get
                Return ResourceManager.GetString("PRODUCTION_CONSUMPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Production/respiration.
        '''</summary>
        Friend ReadOnly Property PRODUCTION_RESPIRATION() As String
            Get
                Return ResourceManager.GetString("PRODUCTION_RESPIRATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select folder for saving results.
        '''</summary>
        Friend ReadOnly Property PROMPT_FOLDER() As String
            Get
                Return ResourceManager.GetString("PROMPT_FOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have not provided all input values to export selected value(s). Please check your selections before trying to save results again..
        '''</summary>
        Friend ReadOnly Property PROMPT_INPUTS() As String
            Get
                Return ResourceManager.GetString("PROMPT_INPUTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proportion nat. mort..
        '''</summary>
        Friend ReadOnly Property PROP_NAT_MORT() As String
            Get
                Return ResourceManager.GetString("PROP_NAT_MORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Residuals.
        '''</summary>
        Friend ReadOnly Property RESIDUALS() As String
            Get
                Return ResourceManager.GetString("RESIDUALS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration.
        '''</summary>
        Friend ReadOnly Property RESPIRATION() As String
            Get
                Return ResourceManager.GetString("RESPIRATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration/assimilation.
        '''</summary>
        Friend ReadOnly Property RESPIRATION_ASSIMILATION() As String
            Get
                Return ResourceManager.GetString("RESPIRATION_ASSIMILATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration/biomass(/year).
        '''</summary>
        Friend ReadOnly Property RESPIRATION_BIOMASS_UNITS() As String
            Get
                Return ResourceManager.GetString("RESPIRATION_BIOMASS_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration(t/km^2/year).
        '''</summary>
        Friend ReadOnly Property RESPIRATION_UNITS() As String
            Get
                Return ResourceManager.GetString("RESPIRATION_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Results.
        '''</summary>
        Friend ReadOnly Property SAVE_RESULTS() As String
            Get
                Return ResourceManager.GetString("SAVE_RESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search rates.
        '''</summary>
        Friend ReadOnly Property SEARCH_RATES() As String
            Get
                Return ResourceManager.GetString("SEARCH_RATES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SearchRates.
        '''</summary>
        Friend ReadOnly Property SEARCHRATES() As String
            Get
                Return ResourceManager.GetString("SEARCHRATES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SS.
        '''</summary>
        Friend ReadOnly Property SS() As String
            Get
                Return ResourceManager.GetString("SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum.
        '''</summary>
        Friend ReadOnly Property SUM() As String
            Get
                Return ResourceManager.GetString("SUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum of squares.
        '''</summary>
        Friend ReadOnly Property SUM_OF_SQUARES() As String
            Get
                Return ResourceManager.GetString("SUM_OF_SQUARES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch.
        '''</summary>
        Friend ReadOnly Property TEXT_CATCH() As String
            Get
                Return ResourceManager.GetString("TEXT_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total catch.
        '''</summary>
        Friend ReadOnly Property TOTAL_CATCH() As String
            Get
                Return ResourceManager.GetString("TOTAL_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Cost.
        '''</summary>
        Friend ReadOnly Property TOTAL_COST() As String
            Get
                Return ResourceManager.GetString("TOTAL_COST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Profit.
        '''</summary>
        Friend ReadOnly Property TOTAL_PROFIT() As String
            Get
                Return ResourceManager.GetString("TOTAL_PROFIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Value.
        '''</summary>
        Friend ReadOnly Property TOTAL_VALUE() As String
            Get
                Return ResourceManager.GetString("TOTAL_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalSS.
        '''</summary>
        Friend ReadOnly Property TOTALSS() As String
            Get
                Return ResourceManager.GetString("TOTALSS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trophic Level.
        '''</summary>
        Friend ReadOnly Property TROPHIC_LEVEL() As String
            Get
                Return ResourceManager.GetString("TROPHIC_LEVEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property TYPE() As String
            Get
                Return ResourceManager.GetString("TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value per fleet.
        '''</summary>
        Friend ReadOnly Property VALUE_PER_FLEET() As String
            Get
                Return ResourceManager.GetString("VALUE_PER_FLEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Values.
        '''</summary>
        Friend ReadOnly Property VALUES() As String
            Get
                Return ResourceManager.GetString("VALUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yearly.
        '''</summary>
        Friend ReadOnly Property YEARLY() As String
            Get
                Return ResourceManager.GetString("YEARLY", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
