'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwENetworkAnalysis.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network analysis.
        '''</summary>
        Friend ReadOnly Property CAPTION() As String
            Get
                Return ResourceManager.GetString("CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AMI.
        '''</summary>
        Friend ReadOnly Property COL_HDR_AMI() As String
            Get
                Return ResourceManager.GetString("COL_HDR_AMI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency (t/km²/year * bits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asc export.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_EXPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asc flow.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_FLOW() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency (flowbits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_FLOWBIT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_FLOWBIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asc import.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_IMPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency (%).
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_PCT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_PCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asc resp.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_RESP() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_RESP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ASCEND_TOTAL() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ASCEND_TOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass.
        '''</summary>
        Friend ReadOnly Property COL_HDR_BIOMASS() As String
            Get
                Return ResourceManager.GetString("COL_HDR_BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacity (t/km²/year * bits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_CAPACITY() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CAPACITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacity.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CAPACITY_ECOSIM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CAPACITY_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacity (flowbits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_CAPACITY_FLOWBIT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CAPACITY_FLOWBIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacity (%).
        '''</summary>
        Friend ReadOnly Property COL_HDR_CAPACITY_PCT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CAPACITY_PCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CATCH() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch detritus req.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CATCH_DET_REQ() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CATCH_DET_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch PPR.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CATCH_PPR() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CATCH_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CONSUM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CONSUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumption by predators.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CONSUM_PREDAT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CONSUM_PREDAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles are linked pathways, starting from a group and returning to it.
        '''</summary>
        Friend ReadOnly Property COL_HDR_CYC() As String
            Get
                Return ResourceManager.GetString("COL_HDR_CYC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer Eff (Det).
        '''</summary>
        Friend ReadOnly Property COL_HDR_DET_TE() As String
            Get
                Return ResourceManager.GetString("COL_HDR_DET_TE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Det. TE (weighted).
        '''</summary>
        Friend ReadOnly Property COL_HDR_DET_TE_W() As String
            Get
                Return ResourceManager.GetString("COL_HDR_DET_TE_W", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detritus (t/km²).
        '''</summary>
        Friend ReadOnly Property COL_HDR_DETRITUS_TKM2() As String
            Get
                Return ResourceManager.GetString("COL_HDR_DETRITUS_TKM2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entropy.
        '''</summary>
        Friend ReadOnly Property COL_HDR_ENTROPY() As String
            Get
                Return ResourceManager.GetString("COL_HDR_ENTROPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend ReadOnly Property COL_HDR_EXPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FCI.
        '''</summary>
        Friend ReadOnly Property COL_HDR_FCI() As String
            Get
                Return ResourceManager.GetString("COL_HDR_FCI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FiB index.
        '''</summary>
        Friend ReadOnly Property COL_HDR_FIB() As String
            Get
                Return ResourceManager.GetString("COL_HDR_FIB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow to detritus.
        '''</summary>
        Friend ReadOnly Property COL_HDR_FLOW_DET() As String
            Get
                Return ResourceManager.GetString("COL_HDR_FLOW_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group name.
        '''</summary>
        Friend ReadOnly Property COL_HDR_GRP_NAME() As String
            Get
                Return ResourceManager.GetString("COL_HDR_GRP_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group name / Trophic level.
        '''</summary>
        Friend ReadOnly Property COL_HDR_GRP_NAME_TRP_LVL() As String
            Get
                Return ResourceManager.GetString("COL_HDR_GRP_NAME_TRP_LVL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impacting / Impacted.
        '''</summary>
        Friend ReadOnly Property COL_HDR_IMPACTING_IMPACTED() As String
            Get
                Return ResourceManager.GetString("COL_HDR_IMPACTING_IMPACTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend ReadOnly Property COL_HDR_IMPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information (bits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_INFO() As String
            Get
                Return ResourceManager.GetString("COL_HDR_INFO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kemptons Q (relative).
        '''</summary>
        Friend ReadOnly Property COL_HDR_KEMPTONS() As String
            Get
                Return ResourceManager.GetString("COL_HDR_KEMPTONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #1.
        '''</summary>
        Friend ReadOnly Property COL_HDR_KEYSTONEINDEX1() As String
            Get
                Return ResourceManager.GetString("COL_HDR_KEYSTONEINDEX1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #2.
        '''</summary>
        Friend ReadOnly Property COL_HDR_KEYSTONEINDEX2() As String
            Get
                Return ResourceManager.GetString("COL_HDR_KEYSTONEINDEX2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #3.
        '''</summary>
        Friend ReadOnly Property COL_HDR_KEYSTONEINDEX3() As String
            Get
                Return ResourceManager.GetString("COL_HDR_KEYSTONEINDEX3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L-index.
        '''</summary>
        Friend ReadOnly Property COL_HDR_LINDEX() As String
            Get
                Return ResourceManager.GetString("COL_HDR_LINDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Living (t/km²).
        '''</summary>
        Friend ReadOnly Property COL_HDR_LIVING_TKM2() As String
            Get
                Return ResourceManager.GetString("COL_HDR_LIVING_TKM2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non-hidden.
        '''</summary>
        Friend ReadOnly Property COL_HDR_NONHIDDEN() As String
            Get
                Return ResourceManager.GetString("COL_HDR_NONHIDDEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. of paths.
        '''</summary>
        Friend ReadOnly Property COL_HDR_NUM_PATH() As String
            Get
                Return ResourceManager.GetString("COL_HDR_NUM_PATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overhead (t/km²/year * bits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ovh export.
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_EXPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ovh flow.
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_FLOW() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overhead (flowbits).
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_FLOWBIT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_FLOWBIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ovh import.
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_IMPORT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overhead (%).
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_PCT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_PCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ovh resp.
        '''</summary>
        Friend ReadOnly Property COL_HDR_OVERHEAD_RESP() As String
            Get
                Return ResourceManager.GetString("COL_HDR_OVERHEAD_RESP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PARAM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PARAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways from the specified group to all top predators.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PATH() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways from primary producer or detritus groups to a selected consumer.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PATH_CONSUM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PATH_CONSUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path length.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PATH_LEN() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PATH_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathway number.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PATH_NUM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PATH_NUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways from primary producer or detritus groups to a selected consumer via a specified prey.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PATH_VIA_PREY() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PATH_VIA_PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCI.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PCI() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PCI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer Eff (PP).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PP_TE() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PP_TE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PP TE (weighted).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PP_TE_W() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PP_TE_W", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR/catch.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_CATCH() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR/consumption.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_COMSUM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_COMSUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR (Det).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_DET() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR (PP).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_PP() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_PP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR/TotPP (%).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_TOTAL_PP() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_TOTAL_PP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR/u. biom.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_U_BIOMASS() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_U_BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PPR/u. catch.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PPR_U_CATCH() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PPR_U_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prim prod.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PRIM_PROD() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PRIM_PROD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prod.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PROD() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PROD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prop flow det.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PROP_FLOW_DET() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PROP_FLOW_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Psust.
        '''</summary>
        Friend ReadOnly Property COL_HDR_PSUST() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PSUST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Psust SD (lower).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PSUST_SDLOWER() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PSUST_SDLOWER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Psust SD (upper).
        '''</summary>
        Friend ReadOnly Property COL_HDR_PSUST_SDUPPER() As String
            Get
                Return ResourceManager.GetString("COL_HDR_PSUST_SDUPPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relative total impact.
        '''</summary>
        Friend ReadOnly Property COL_HDR_RELTOTALIMPACT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_RELTOTALIMPACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration.
        '''</summary>
        Friend ReadOnly Property COL_HDR_RESP() As String
            Get
                Return ResourceManager.GetString("COL_HDR_RESP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resp.
        '''</summary>
        Friend ReadOnly Property COL_HDR_RESP_ECOSIM() As String
            Get
                Return ResourceManager.GetString("COL_HDR_RESP_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source.
        '''</summary>
        Friend ReadOnly Property COL_HDR_SOURCE() As String
            Get
                Return ResourceManager.GetString("COL_HDR_SOURCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source \ Trophic level.
        '''</summary>
        Friend ReadOnly Property COL_HDR_SOURCE_TRP_LVL() As String
            Get
                Return ResourceManager.GetString("COL_HDR_SOURCE_TRP_LVL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throughput.
        '''</summary>
        Friend ReadOnly Property COL_HDR_THROUGHPUT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_THROUGHPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throughput (t/km²/year).
        '''</summary>
        Friend ReadOnly Property COL_HDR_THROUGHPUT_UNIT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_THROUGHPUT_UNIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TL.
        '''</summary>
        Friend ReadOnly Property COL_HDR_TL() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TL of catch.
        '''</summary>
        Friend ReadOnly Property COL_HDR_TLc() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TLc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer Eff (Total).
        '''</summary>
        Friend ReadOnly Property COL_HDR_TOT_TE() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TOT_TE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total TE (weigthed).
        '''</summary>
        Friend ReadOnly Property COL_HDR_TOT_TE_W() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TOT_TE_W", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total (t/km²).
        '''</summary>
        Friend ReadOnly Property COL_HDR_TOTAL_TKM2() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TOTAL_TKM2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total (t/km²/year).
        '''</summary>
        Friend ReadOnly Property COL_HDR_TOTAL_TKM2YR() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TOTAL_TKM2YR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trophic level.
        '''</summary>
        Friend ReadOnly Property COL_HDR_TRP_LVL() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TRP_LVL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trophic level \ Flow.
        '''</summary>
        Friend ReadOnly Property COL_HDR_TRP_LVL_FLOW() As String
            Get
                Return ResourceManager.GetString("COL_HDR_TRP_LVL_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit.
        '''</summary>
        Friend ReadOnly Property COL_HDR_UNIT() As String
            Get
                Return ResourceManager.GetString("COL_HDR_UNIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property COL_HDR_VALUE() As String
            Get
                Return ResourceManager.GetString("COL_HDR_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend ReadOnly Property COL_HDR_YEAR() As String
            Get
                Return ResourceManager.GetString("COL_HDR_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property EwENetworkAnalysis() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("EwENetworkAnalysis", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMF image files (*.emf)|*.emf|All files (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_EMF() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_EMF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis plug-in.
        '''</summary>
        Friend ReadOnly Property GENERIC_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("GENERIC_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annual.
        '''</summary>
        Friend ReadOnly Property HEADER_ANNUAL() As String
            Get
                Return ResourceManager.GetString("HEADER_ANNUAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monthly.
        '''</summary>
        Friend ReadOnly Property HEADER_MONTHLY() As String
            Get
                Return ResourceManager.GetString("HEADER_MONTHLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency on flow.
        '''</summary>
        Friend ReadOnly Property LBL_ASCEND_FLOW() As String
            Get
                Return ResourceManager.GetString("LBL_ASCEND_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to accum.
        '''</summary>
        Friend ReadOnly Property LBL_BACCUM() As String
            Get
                Return ResourceManager.GetString("LBL_BACCUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to biomass.
        '''</summary>
        Friend ReadOnly Property LBL_BIOMASS() As String
            Get
                Return ResourceManager.GetString("LBL_BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch detritus required.
        '''</summary>
        Friend ReadOnly Property LBL_CATCH_DET_REQ() As String
            Get
                Return ResourceManager.GetString("LBL_CATCH_DET_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch PPR.
        '''</summary>
        Friend ReadOnly Property LBL_CATCH_PPR() As String
            Get
                Return ResourceManager.GetString("LBL_CATCH_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to consumption.
        '''</summary>
        Friend ReadOnly Property LBL_CONS() As String
            Get
                Return ResourceManager.GetString("LBL_CONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycle finding progress:.
        '''</summary>
        Friend ReadOnly Property LBL_CYC_FIND_PRGR() As String
            Get
                Return ResourceManager.GetString("LBL_CYC_FIND_PRGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecosim network analysis (with PPR Est) progress:.
        '''</summary>
        Friend ReadOnly Property LBL_ECOSIM_NA_W_PPR_EST_PRGR() As String
            Get
                Return ResourceManager.GetString("LBL_ECOSIM_NA_W_PPR_EST_PRGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecosim network analysis (without PPR Est) progress:.
        '''</summary>
        Friend ReadOnly Property LBL_ECOSIM_NA_WO_PPR_EST_PRGR() As String
            Get
                Return ResourceManager.GetString("LBL_ECOSIM_NA_WO_PPR_EST_PRGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exports and catches.
        '''</summary>
        Friend ReadOnly Property LBL_EXPORT() As String
            Get
                Return ResourceManager.GetString("LBL_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FCI.
        '''</summary>
        Friend ReadOnly Property LBL_FCI() As String
            Get
                Return ResourceManager.GetString("LBL_FCI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FIB index.
        '''</summary>
        Friend ReadOnly Property LBL_FIB_INDX() As String
            Get
                Return ResourceManager.GetString("LBL_FIB_INDX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to flow from detritus.
        '''</summary>
        Friend ReadOnly Property LBL_FLOWDET() As String
            Get
                Return ResourceManager.GetString("LBL_FLOWDET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impacted group.
        '''</summary>
        Friend ReadOnly Property LBL_IMPACTED_GP() As String
            Get
                Return ResourceManager.GetString("LBL_IMPACTED_GP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impacting group.
        '''</summary>
        Friend ReadOnly Property LBL_IMPACTING_GP() As String
            Get
                Return ResourceManager.GetString("LBL_IMPACTING_GP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to import.
        '''</summary>
        Friend ReadOnly Property LBL_IMPORT() As String
            Get
                Return ResourceManager.GetString("LBL_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}: {1}.
        '''</summary>
        Friend ReadOnly Property LBL_INDEXED() As String
            Get
                Return ResourceManager.GetString("LBL_INDEXED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kemptons Q.
        '''</summary>
        Friend ReadOnly Property LBL_KEMPTONS_Q() As String
            Get
                Return ResourceManager.GetString("LBL_KEMPTONS_Q", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #1 (Libralato et al, 2006).
        '''</summary>
        Friend ReadOnly Property LBL_KEYSTONE1() As String
            Get
                Return ResourceManager.GetString("LBL_KEYSTONE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #2 (Power et al, 1996) .
        '''</summary>
        Friend ReadOnly Property LBL_KEYSTONE2() As String
            Get
                Return ResourceManager.GetString("LBL_KEYSTONE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group rank by keystone index #3 (Valls et al, 2015) .
        '''</summary>
        Friend ReadOnly Property LBL_KEYSTONE3() As String
            Get
                Return ResourceManager.GetString("LBL_KEYSTONE3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss of production (relative).
        '''</summary>
        Friend ReadOnly Property LBL_LINDEX_REL() As String
            Get
                Return ResourceManager.GetString("LBL_LINDEX_REL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Months.
        '''</summary>
        Friend ReadOnly Property LBL_MONTHS() As String
            Get
                Return ResourceManager.GetString("LBL_MONTHS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network analysis indices.
        '''</summary>
        Friend ReadOnly Property LBL_NA_INDIC() As String
            Get
                Return ResourceManager.GetString("LBL_NA_INDIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network analysis progress:.
        '''</summary>
        Friend ReadOnly Property LBL_NA_PRGR() As String
            Get
                Return ResourceManager.GetString("LBL_NA_PRGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Negative.
        '''</summary>
        Friend ReadOnly Property LBL_NEGATIVE() As String
            Get
                Return ResourceManager.GetString("LBL_NEGATIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways &amp;from:.
        '''</summary>
        Friend ReadOnly Property LBL_PATH_FROM() As String
            Get
                Return ResourceManager.GetString("LBL_PATH_FROM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways &amp;leading to:.
        '''</summary>
        Friend ReadOnly Property LBL_PATH_TO() As String
            Get
                Return ResourceManager.GetString("LBL_PATH_TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;via:.
        '''</summary>
        Friend ReadOnly Property LBL_PATH_VIA() As String
            Get
                Return ResourceManager.GetString("LBL_PATH_VIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positive.
        '''</summary>
        Friend ReadOnly Property LBL_POSITIVE() As String
            Get
                Return ResourceManager.GetString("LBL_POSITIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary production calculation progress:.
        '''</summary>
        Friend ReadOnly Property LBL_PPR_CAL_PRGR() As String
            Get
                Return ResourceManager.GetString("LBL_PPR_CAL_PRGR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to predation.
        '''</summary>
        Friend ReadOnly Property LBL_PREDATION() As String
            Get
                Return ResourceManager.GetString("LBL_PREDATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relative total impact.
        '''</summary>
        Friend ReadOnly Property LBL_RELTOTALIMPACT() As String
            Get
                Return ResourceManager.GetString("LBL_RELTOTALIMPACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to respiration.
        '''</summary>
        Friend ReadOnly Property LBL_RESP() As String
            Get
                Return ResourceManager.GetString("LBL_RESP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TE.
        '''</summary>
        Friend ReadOnly Property LBL_TE() As String
            Get
                Return ResourceManager.GetString("LBL_TE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TL.
        '''</summary>
        Friend ReadOnly Property LBL_TL() As String
            Get
                Return ResourceManager.GetString("LBL_TL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TL of catch.
        '''</summary>
        Friend ReadOnly Property LBL_TL_CATCH() As String
            Get
                Return ResourceManager.GetString("LBL_TL_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total catch.
        '''</summary>
        Friend ReadOnly Property LBL_TOTAL_CATCH() As String
            Get
                Return ResourceManager.GetString("LBL_TOTAL_CATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TST(%).
        '''</summary>
        Friend ReadOnly Property LBL_TST() As String
            Get
                Return ResourceManager.GetString("LBL_TST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Graph c&amp;ontent.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #&amp;1  (Libralato et al, 2006).
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_KEYSTONE1() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_KEYSTONE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #&amp;2  (Power et al, 1996).
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_KEYSTONE2() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_KEYSTONE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystone index #&amp;3 (Valls et al, 2015).
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_KEYSTONE3() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_KEYSTONE3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Max. trophic level.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_MAXTL() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_MAXTL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show &amp;biomass.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_SHOW_BIOMASS() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_SHOW_BIOMASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show biomass &amp;accumulation.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_SHOW_BIOMASSACCUM() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_SHOW_BIOMASSACCUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show &amp;import.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_SHOW_IMPORT() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_SHOW_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show &amp;TST(%).
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_SHOW_TST() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_SHOW_TST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total &amp;impact over Biomass.
        '''</summary>
        Friend ReadOnly Property MNU_CONTENT_TOTIMPACT_OVER_B() As String
            Get
                Return ResourceManager.GetString("MNU_CONTENT_TOTIMPACT_OVER_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Graph &amp;style.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Circles.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE_CIRCLES() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE_CIRCLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Circles, scaled to &amp;Biomass.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE_CIRCLES_SCALED() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE_CIRCLES_SCALED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Collapse detritus.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE_DETRITUS_COLLAPSE() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE_DETRITUS_COLLAPSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Expand detritus.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE_DETRITUS_EXPAND() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE_DETRITUS_EXPAND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Numbers.
        '''</summary>
        Friend ReadOnly Property MNU_STYLE_NUMBERS() As String
            Get
                Return ResourceManager.GetString("MNU_STYLE_NUMBERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property N_Asponsors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N_Asponsors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis.
        '''</summary>
        Friend ReadOnly Property NAVITEM_ROOT() As String
            Get
                Return ResourceManager.GetString("NAVITEM_ROOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascendency.
        '''</summary>
        Friend ReadOnly Property PAGE_ASC() As String
            Get
                Return ResourceManager.GetString("PAGE_ASC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By group.
        '''</summary>
        Friend ReadOnly Property PAGE_ASC_GROUP() As String
            Get
                Return ResourceManager.GetString("PAGE_ASC_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend ReadOnly Property PAGE_ASC_TOTAL() As String
            Get
                Return ResourceManager.GetString("PAGE_ASC_TOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer &lt;- prey &lt;- TL1.
        '''</summary>
        Friend ReadOnly Property PAGE_CP_CPTL11() As String
            Get
                Return ResourceManager.GetString("PAGE_CP_CPTL11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consumer &lt;- TL1.
        '''</summary>
        Friend ReadOnly Property PAGE_CP_CTL1() As String
            Get
                Return ResourceManager.GetString("PAGE_CP_CTL1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles.
        '''</summary>
        Friend ReadOnly Property PAGE_CP_CYCLES() As String
            Get
                Return ResourceManager.GetString("PAGE_CP_CYCLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathways.
        '''</summary>
        Friend ReadOnly Property PAGE_CP_PATHWAYS() As String
            Get
                Return ResourceManager.GetString("PAGE_CP_PATHWAYS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Top predation &lt;- prey.
        '''</summary>
        Friend ReadOnly Property PAGE_CP_TOPPRED() As String
            Get
                Return ResourceManager.GetString("PAGE_CP_TOPPRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credits.
        '''</summary>
        Friend ReadOnly Property PAGE_CREDITS() As String
            Get
                Return ResourceManager.GetString("PAGE_CREDITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles (all).
        '''</summary>
        Friend ReadOnly Property PAGE_CYC_ALL() As String
            Get
                Return ResourceManager.GetString("PAGE_CYC_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles (living).
        '''</summary>
        Friend ReadOnly Property PAGE_CYC_LIVING() As String
            Get
                Return ResourceManager.GetString("PAGE_CYC_LIVING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles and pathways.
        '''</summary>
        Friend ReadOnly Property PAGE_CYCLES_PATHWAYS() As String
            Get
                Return ResourceManager.GetString("PAGE_CYCLES_PATHWAYS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycles and path length.
        '''</summary>
        Friend ReadOnly Property PAGE_CYCPATH_LEN() As String
            Get
                Return ResourceManager.GetString("PAGE_CYCPATH_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecosim network analysis.
        '''</summary>
        Friend ReadOnly Property PAGE_ECOSIM_NA() As String
            Get
                Return ResourceManager.GetString("PAGE_ECOSIM_NA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indexes with primary production required.
        '''</summary>
        Friend ReadOnly Property PAGE_ECOSIM_NA_WITH_PPR() As String
            Get
                Return ResourceManager.GetString("PAGE_ECOSIM_NA_WITH_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indexes without primary production required.
        '''</summary>
        Friend ReadOnly Property PAGE_ECOSIM_NA_WO_PPR() As String
            Get
                Return ResourceManager.GetString("PAGE_ECOSIM_NA_WO_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flows and biomasses.
        '''</summary>
        Friend ReadOnly Property PAGE_FB() As String
            Get
                Return ResourceManager.GetString("PAGE_FB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass pyramid.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_BIOMPMD() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_BIOMPMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass by trophic level.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_BIOMTL() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_BIOMTL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch pyramid.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_CATCHPMD() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_CATCHPMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch by trophic level.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_CATCHTL() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_CATCHTL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow pyramid.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_FLOWPMD() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_FLOWPMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From all combined.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_FROMCOMBINED() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_FROMCOMBINED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From detritus.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_FROMDET() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_FROMDET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From primary producers.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_FROMPP() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_FROMPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lindeman spine.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_LINDEMAN() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_LINDEMAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer efficiency.
        '''</summary>
        Friend ReadOnly Property PAGE_FB_TRANSEFF() As String
            Get
                Return ResourceManager.GetString("PAGE_FB_TRANSEFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow from detritus.
        '''</summary>
        Friend ReadOnly Property PAGE_FLOWDET() As String
            Get
                Return ResourceManager.GetString("PAGE_FLOWDET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystoneness.
        '''</summary>
        Friend ReadOnly Property PAGE_KEYSTONENESS() As String
            Get
                Return ResourceManager.GetString("PAGE_KEYSTONENESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystoneness graph.
        '''</summary>
        Friend ReadOnly Property PAGE_KEYSTONENESS_GRAPH() As String
            Get
                Return ResourceManager.GetString("PAGE_KEYSTONENESS_GRAPH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keystoneness table.
        '''</summary>
        Friend ReadOnly Property PAGE_KEYSTONENESS_TABLE() As String
            Get
                Return ResourceManager.GetString("PAGE_KEYSTONENESS_TABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss of Production index.
        '''</summary>
        Friend ReadOnly Property PAGE_LINDEX() As String
            Get
                Return ResourceManager.GetString("PAGE_LINDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mixed trophic impact.
        '''</summary>
        Friend ReadOnly Property PAGE_MTI() As String
            Get
                Return ResourceManager.GetString("PAGE_MTI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impact data.
        '''</summary>
        Friend ReadOnly Property PAGE_MTI_IMPACT() As String
            Get
                Return ResourceManager.GetString("PAGE_MTI_IMPACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mixed trophic impact plot.
        '''</summary>
        Friend ReadOnly Property PAGE_MTI_PLOT() As String
            Get
                Return ResourceManager.GetString("PAGE_MTI_PLOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mixed trophic impact plot (EwE5).
        '''</summary>
        Friend ReadOnly Property PAGE_MTI_PLOTEWE5() As String
            Get
                Return ResourceManager.GetString("PAGE_MTI_PLOTEWE5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary production required.
        '''</summary>
        Friend ReadOnly Property PAGE_PPR() As String
            Get
                Return ResourceManager.GetString("PAGE_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For consumption of all groups.
        '''</summary>
        Friend ReadOnly Property PAGE_PPR_CONS() As String
            Get
                Return ResourceManager.GetString("PAGE_PPR_CONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For harvest of all groups.
        '''</summary>
        Friend ReadOnly Property PAGE_PPR_HARV() As String
            Get
                Return ResourceManager.GetString("PAGE_PPR_HARV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Absolute flows.
        '''</summary>
        Friend ReadOnly Property PAGE_TL_ABSFLOWS() As String
            Get
                Return ResourceManager.GetString("PAGE_TL_ABSFLOWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relative flows.
        '''</summary>
        Friend ReadOnly Property PAGE_TL_RELFLOWS() As String
            Get
                Return ResourceManager.GetString("PAGE_TL_RELFLOWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trophic level decomposition.
        '''</summary>
        Friend ReadOnly Property PAGE_TLDECOMP() As String
            Get
                Return ResourceManager.GetString("PAGE_TLDECOMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to launch application &apos;{0}&apos;: {1}.
        '''</summary>
        Friend ReadOnly Property PROMPT_APPLAUNCH_FAILED() As String
            Get
                Return ResourceManager.GetString("PROMPT_APPLAUNCH_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compute all cycles? This may be very time consuming for larger models..
        '''</summary>
        Friend ReadOnly Property PROMPT_COMPUTE_ALL_CYCLES() As String
            Get
                Return ResourceManager.GetString("PROMPT_COMPUTE_ALL_CYCLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display all groups (yes) or hidden groups only (No)?.
        '''</summary>
        Friend ReadOnly Property PROMPT_DISPLAY_ALL_HIDDEN_GROUPS() As String
            Get
                Return ResourceManager.GetString("PROMPT_DISPLAY_ALL_HIDDEN_GROUPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predatory cycling index cannot be calculated..
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_CYCLING() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_CYCLING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis can not be run before Ecopath.
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_ECOPATH() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_ECOPATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while running Network Analysis for Ecosim: {0}.
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_ECOSIM() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis for Ecosim could not be initialized because of a problem in Network Analysis.
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_ECOSIM_INIT() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_ECOSIM_INIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis not initialized properly.
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_INITIALIZE() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_INITIALIZE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no utilized primary producers. Network analysis cannot continue..
        '''</summary>
        Friend ReadOnly Property PROMPT_ERROR_PP() As String
            Get
                Return ResourceManager.GetString("PROMPT_ERROR_PP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estimate primary production required? This may be very time consuming for larger models..
        '''</summary>
        Friend ReadOnly Property PROMPT_ESTIMATE_PPR() As String
            Get
                Return ResourceManager.GetString("PROMPT_ESTIMATE_PPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to create file &apos;{0}&apos;: {1}.
        '''</summary>
        Friend ReadOnly Property PROMPT_FILECREATE_FAILED() As String
            Get
                Return ResourceManager.GetString("PROMPT_FILECREATE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please load an Ecosim scenario before running Network Analysis for Ecosim..
        '''</summary>
        Friend ReadOnly Property PROMPT_LOAD_ECOSIM() As String
            Get
                Return ResourceManager.GetString("PROMPT_LOAD_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis may run slow on complex diet matrices, and may take several hours to days (!) to complete. Are you sure you want to continue?.
        '''</summary>
        Friend ReadOnly Property PROMPT_NETWORK_COMPLEXDIET() As String
            Get
                Return ResourceManager.GetString("PROMPT_NETWORK_COMPLEXDIET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Network Analysis results as annual averages?.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_ANNUAL_AVERAGES() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_ANNUAL_AVERAGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select destination to save Network Analysis results CSV file.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_DESTINATION() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_DESTINATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis failed to save indices to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis cannot access destination &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_NOACCESS() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_NOACCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Analysis indices saved to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property PROMPT_SAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("PROMPT_SAVE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All flows.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_ALL_FLOWS() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_ALL_FLOWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detritus.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_DET() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_EXPORT() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracted to break cycles.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_EXTRACT_BREAK_CYC() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_EXTRACT_BREAK_CYC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finn&apos;s cycling index.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_FINN_CYC_INDX() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_FINN_CYC_INDX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finn&apos;s mean path length.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_FINN_MEAN_PATH_LEN() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_FINN_MEAN_PATH_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finn&apos;s straight-through path length.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_FINN_STR_THRU_PATH_LEN() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_FINN_STR_THRU_PATH_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_IMPORT() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input TL II+ (not in throughput).
        '''</summary>
        Friend ReadOnly Property ROW_HDR_INPUT_TRP_LVL_II_PLUS() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_INPUT_TRP_LVL_II_PLUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal flow.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_INTN_FLOW() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_INTN_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mean length of pathways = Total number of arrows / Total number of pathways.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_MEAN_PATH_LEN() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_MEAN_PATH_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No pathways found.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_NO_PATH_FOUND() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_NO_PATH_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not applicable.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_NOT_APP() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_NOT_APP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (%).
        '''</summary>
        Friend ReadOnly Property ROW_HDR_PCT() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_PCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predatory cycling index.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_PRED_CYC_INDX() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_PRED_CYC_INDX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Producer.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_PRODUCER() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_PRODUCER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiration.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_RESP() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_RESP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_SUM() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_SUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throughput cycled (excluding detritus).
        '''</summary>
        Friend ReadOnly Property ROW_HDR_THROUGHPUT_CYC_LIV() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_THROUGHPUT_CYC_LIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throughput cycled (including detritus).
        '''</summary>
        Friend ReadOnly Property ROW_HDR_THROUGHPUT_CYC_TOTAL() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_THROUGHPUT_CYC_TOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_TOTAL() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_TOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total number of pathways.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_TOTAL_NUM_PATH() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_TOTAL_NUM_PATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total throughput.
        '''</summary>
        Friend ReadOnly Property ROW_HDR_TOTAL_THROUGHPUT() As String
            Get
                Return ResourceManager.GetString("ROW_HDR_TOTAL_THROUGHPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.sams.ac.uk/.
        '''</summary>
        Friend ReadOnly Property SAMS_URL() As String
            Get
                Return ResourceManager.GetString("SAMS_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding pathway cycles....
        '''</summary>
        Friend ReadOnly Property STATUS_FINDING_PATHWAY_CYCLES() As String
            Get
                Return ResourceManager.GetString("STATUS_FINDING_PATHWAY_CYCLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding pathways....
        '''</summary>
        Friend ReadOnly Property STATUS_FINDING_PATHWAYS() As String
            Get
                Return ResourceManager.GetString("STATUS_FINDING_PATHWAYS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding pathways for &apos;{0}&apos; via &apos;{1}&apos;....
        '''</summary>
        Friend ReadOnly Property STATUS_FINDING_PATHWAYS_CONSPREY() As String
            Get
                Return ResourceManager.GetString("STATUS_FINDING_PATHWAYS_CONSPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding pathways to consumer &apos;{0}&apos;....
        '''</summary>
        Friend ReadOnly Property STATUS_FINDING_PATHWAYS_CONSUMER() As String
            Get
                Return ResourceManager.GetString("STATUS_FINDING_PATHWAYS_CONSUMER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding pathways for prey &apos;{0}&apos;....
        '''</summary>
        Friend ReadOnly Property STATUS_FINDING_PATHWAYS_PREY() As String
            Get
                Return ResourceManager.GetString("STATUS_FINDING_PATHWAYS_PREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running Network Analysis eqPP....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_EQPP() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_EQPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running Network Analysis Lindeman....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_LINDEMAN() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_LINDEMAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running Network Analysis....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_NA() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_NA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running Network Analysis....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_NETWORKANALYSIS() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_NETWORKANALYSIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running Network Analysis Ulanow....
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING_ULANOW() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING_ULANOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating UI....
        '''</summary>
        Friend ReadOnly Property STATUS_UPDATING_UI() As String
            Get
                Return ResourceManager.GetString("STATUS_UPDATING_UI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to      From detritus: {0}%.
        '''</summary>
        Friend ReadOnly Property STR_FROM_DET() As String
            Get
                Return ResourceManager.GetString("STR_FROM_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to      From primary producers: {0}%.
        '''</summary>
        Friend ReadOnly Property STR_FROM_PRIM_PRODUCER() As String
            Get
                Return ResourceManager.GetString("STR_FROM_PRIM_PRODUCER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to none.
        '''</summary>
        Friend ReadOnly Property STR_NONE() As String
            Get
                Return ResourceManager.GetString("STR_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % of throughput without detritus.
        '''</summary>
        Friend ReadOnly Property STR_PCT_THROUGHPUT_LIV() As String
            Get
                Return ResourceManager.GetString("STR_PCT_THROUGHPUT_LIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to % of total throughput.
        '''</summary>
        Friend ReadOnly Property STR_PCT_TOTAL_THROUGHPUT() As String
            Get
                Return ResourceManager.GetString("STR_PCT_TOTAL_THROUGHPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proportion of total flow originating from detritus: .
        '''</summary>
        Friend ReadOnly Property STR_PROP_TOTAL_FLOW() As String
            Get
                Return ResourceManager.GetString("STR_PROP_TOTAL_FLOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t/km²/year.
        '''</summary>
        Friend ReadOnly Property STR_T_KM2_YR() As String
            Get
                Return ResourceManager.GetString("STR_T_KM2_YR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to      Total: {0}%.
        '''</summary>
        Friend ReadOnly Property STR_TOTAL() As String
            Get
                Return ResourceManager.GetString("STR_TOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer efficiencies (calculated as geometric mean for TL II-IV).
        '''</summary>
        Friend ReadOnly Property STR_TRANSFER_EFF() As String
            Get
                Return ResourceManager.GetString("STR_TRANSFER_EFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to with detritus.
        '''</summary>
        Friend ReadOnly Property STR_W_DET() As String
            Get
                Return ResourceManager.GetString("STR_W_DET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to without detritus.
        '''</summary>
        Friend ReadOnly Property STR_WO_DET() As String
            Get
                Return ResourceManager.GetString("STR_WO_DET", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
