'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEShapeGridPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all egg produciton functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_EGGPROD() As String
            Get
                Return ResourceManager.GetString("DESC_EGGPROD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all fishing effort functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_FISHING_EFFORT() As String
            Get
                Return ResourceManager.GetString("DESC_FISHING_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all fishing mortality functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_FISHMORT() As String
            Get
                Return ResourceManager.GetString("DESC_FISHMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all forcing functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_FORCING() As String
            Get
                Return ResourceManager.GetString("DESC_FORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all functional response functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_HABCAP() As String
            Get
                Return ResourceManager.GetString("DESC_HABCAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all price elasticity functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_MED_LANDINGS() As String
            Get
                Return ResourceManager.GetString("DESC_MED_LANDINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all mediation functions in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_MED_PREDPREY() As String
            Get
                Return ResourceManager.GetString("DESC_MED_PREDPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display of all loaded time series in a grid format.
        '''</summary>
        Friend ReadOnly Property DESC_TIMESERIES() As String
            Get
                Return ResourceManager.GetString("DESC_TIMESERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Egg production functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_EGGPROD() As String
            Get
                Return ResourceManager.GetString("GRID_EGGPROD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing effort functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_FISHING_EFFORT() As String
            Get
                Return ResourceManager.GetString("GRID_FISHING_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing mortality functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_FISHMORT() As String
            Get
                Return ResourceManager.GetString("GRID_FISHMORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Functional responses grid.
        '''</summary>
        Friend ReadOnly Property GRID_FNRESPONSES() As String
            Get
                Return ResourceManager.GetString("GRID_FNRESPONSES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forcing functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_FORCING() As String
            Get
                Return ResourceManager.GetString("GRID_FORCING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price elasticity functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_MED_LANDINGS() As String
            Get
                Return ResourceManager.GetString("GRID_MED_LANDINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mediation functions grid.
        '''</summary>
        Friend ReadOnly Property GRID_MED_PREDPREY() As String
            Get
                Return ResourceManager.GetString("GRID_MED_PREDPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time series grid.
        '''</summary>
        Friend ReadOnly Property GRID_TIMESERIES() As String
            Get
                Return ResourceManager.GetString("GRID_TIMESERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interval.
        '''</summary>
        Friend ReadOnly Property HEADER_INTERVAL() As String
            Get
                Return ResourceManager.GetString("HEADER_INTERVAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2nd target.
        '''</summary>
        Friend ReadOnly Property HEADER_TARGET_SECOND() As String
            Get
                Return ResourceManager.GetString("HEADER_TARGET_SECOND", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
