' ===============================================================================
' This file is part of Ecopath with Ecosim (EwE)
'
' EwE is free software: you can redistribute it and/or modify it under the terms
' of the GNU General Public License version 2 as published by the Free Software 
' Foundation.
'
' EwE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
' without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
' PURPOSE. See the GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License along with EwE.
' If not, see <http://www.gnu.org/licenses/gpl-2.0.html>. 
'
' Copyright 1991- 
'    UBC Institute for the Oceans and Fisheries, Vancouver BC, Canada, and
'    Ecopath International Initiative, Barcelona, Spain
' ===============================================================================
'

#Region " Imports "

Option Strict On

#End Region ' Imports

Namespace Database

    ''' -----------------------------------------------------------------------
    ''' <summary>
    ''' Interface for definining an import engine.
    ''' </summary>
    ''' -----------------------------------------------------------------------
    Public Interface IModelImporter

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' Connects the importer to an external source with model data to import.
        ''' </summary>
        ''' <returns>True if successful.</returns>
        ''' <remarks>
        ''' Any connection established via the Open method must be disconnected 
        ''' via the <see cref="Close"/>.
        ''' </remarks>
        ''' -------------------------------------------------------------------
        Function Open(ByVal strSource As String) As Boolean

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' Disconnects the importer from its source document.
        ''' </summary>
        ''' <remarks>
        ''' Any database connection established via the <see cref="Open"/>
        ''' method must be disconnected via the Close method.
        ''' </remarks>
        ''' -------------------------------------------------------------------
        Sub Close()

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' States whether the importer was connected to its source document 
        ''' via the <see cref="Open">Open</see> method.
        ''' </summary>
        ''' -------------------------------------------------------------------
        Function IsOpen() As Boolean

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' Perform the actual import.
        ''' </summary>
        ''' <param name="info"><see cref="cExternalModelInfo">Info</see> describing
        ''' the model to import.</param>
        ''' <param name="db">The database to import a model into.</param>
        ''' <param name="strLogfileName">Log file generated by the import process.</param>
        ''' <returns>True if successful.</returns>
        ''' -------------------------------------------------------------------
        Function Import(ByVal info As cExternalModelInfo, _
                        ByVal db As cEwEDatabase, _
                        ByRef strLogfileName As String) As Boolean

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' Get a <see cref="cExternalModelInfo">descriptive list of models</see> 
        ''' that can be imported from an attached source.
        ''' </summary>
        ''' <returns></returns>
        ''' -------------------------------------------------------------------
        Function Models() As cExternalModelInfo()

        ''' -------------------------------------------------------------------
        ''' <summary>
        ''' Returns whether an importer can import from a given source.
        ''' </summary>
        ''' <param name="strSource">Source to explore.</param>
        ''' <returns>True if an importer can import from the given source.</returns>
        ''' -------------------------------------------------------------------
        Function CanImportFrom(ByVal strSource As String) As Boolean

    End Interface

    ''' -----------------------------------------------------------------------
    ''' <summary>
    ''' Helper class, provides information of an external importable model.
    ''' </summary>
    ''' -----------------------------------------------------------------------
    Public Class cExternalModelInfo

        Private m_strID As String = ""
        Private m_strName As String = ""
        Private m_strDescription As String = ""
        Private m_nScenarios As Integer = 0

        ''' ---------------------------------------------------------------
        ''' <summary>
        ''' Constructor, initializes a new instance of this class.
        ''' </summary>
        ''' <param name="strID">EwE5 modelName for this model.</param>
        ''' <param name="strName">EwE5 modelTitle for this model.</param>
        ''' <param name="strDescription">EwE5 model Remarks for this model.</param>
        ''' <param name="nScenarios">Number of EwE5 scenarios in this model.</param>
        ''' ---------------------------------------------------------------
        Public Sub New(ByVal strID As String, ByVal strName As String, ByVal strDescription As String, ByVal nScenarios As Integer)
            Me.m_strID = strID
            Me.m_strName = strName
            Me.m_strDescription = strDescription
            Me.m_nScenarios = nScenarios
        End Sub

        ''' ---------------------------------------------------------------
        ''' <summary>
        ''' Gets the internal model ID (EwE5 field modelName) for this model.
        ''' </summary>
        ''' ---------------------------------------------------------------
        Public ReadOnly Property ID() As String
            Get
                Return Me.m_strID
            End Get
        End Property

        ''' ---------------------------------------------------------------
        ''' <summary>
        ''' Gets the human readable model name (EwE5 field modelTitle) for this model.
        ''' </summary>
        ''' ---------------------------------------------------------------
        Public ReadOnly Property Name() As String
            Get
                Return Me.m_strName
            End Get
        End Property

        ''' ---------------------------------------------------------------
        ''' <summary>
        ''' Gets the model description (EwE5 field Remarks) for this model.
        ''' </summary>
        ''' ---------------------------------------------------------------
        Public ReadOnly Property Description() As String
            Get
                Return Me.m_strDescription
            End Get
        End Property

        ''' ---------------------------------------------------------------
        ''' <summary>
        ''' Gets the number of scenarios in this model.
        ''' </summary>
        ''' ---------------------------------------------------------------
        Public ReadOnly Property NumScenarios() As Integer
            Get
                Return Me.m_nScenarios
            End Get
        End Property

    End Class

End Namespace ' Database
