'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WoRMSWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://aphia/v1.0", ConfigurationName:="WoRMSWebService.AphiaNameServicePortType")>  _
    Public Interface AphiaNameServicePortType
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaID) of message getAphiaIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function getAphiaID(ByVal request As WoRMSWebService.getAphiaIDRequest) As WoRMSWebService.getAphiaIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaRecordsRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaRecords", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaRecords(ByVal request As WoRMSWebService.getAphiaRecordsRequest) As WoRMSWebService.getAphiaRecordsResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaName) of message getAphiaNameByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaNameByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaNameByID(ByVal request As WoRMSWebService.getAphiaNameByIDRequest) As WoRMSWebService.getAphiaNameByIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecord) of message getAphiaRecordByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaRecordByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaRecordByID(ByVal request As WoRMSWebService.getAphiaRecordByIDRequest) As WoRMSWebService.getAphiaRecordByIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecord) of message getAphiaRecordByTSNRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaRecordByTSN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaRecordByTSN(ByVal request As WoRMSWebService.getAphiaRecordByTSNRequest) As WoRMSWebService.getAphiaRecordByTSNResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaMatches) of message getAphiaRecordsByNamesRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaRecordsByNames", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaRecordsByNames(ByVal request As WoRMSWebService.getAphiaRecordsByNamesRequest) As WoRMSWebService.getAphiaRecordsByNamesResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaRecordsByVernacularRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaRecordsByVernacular", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaRecordsByVernacular(ByVal request As WoRMSWebService.getAphiaRecordsByVernacularRequest) As WoRMSWebService.getAphiaRecordsByVernacularResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/Classification) of message getAphiaClassificationByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaClassificationByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaClassificationByID(ByVal request As WoRMSWebService.getAphiaClassificationByIDRequest) As WoRMSWebService.getAphiaClassificationByIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/Sources) of message getSourcesByAphiaIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getSourcesByAphiaID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getSourcesByAphiaID(ByVal request As WoRMSWebService.getSourcesByAphiaIDRequest) As WoRMSWebService.getSourcesByAphiaIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaSynonymsByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaSynonymsByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaSynonymsByID(ByVal request As WoRMSWebService.getAphiaSynonymsByIDRequest) As WoRMSWebService.getAphiaSynonymsByIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaVernaculars) of message getAphiaVernacularsByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaVernacularsByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaVernacularsByID(ByVal request As WoRMSWebService.getAphiaVernacularsByIDRequest) As WoRMSWebService.getAphiaVernacularsByIDResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://aphia/v1.0/AphiaRecords) of message getAphiaChildrenByIDRequest does not match the default value (http://aphia/v1.0)
        <System.ServiceModel.OperationContractAttribute(Action:="getAphiaChildrenByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vernacular)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Source))>  _
        Function getAphiaChildrenByID(ByVal request As WoRMSWebService.getAphiaChildrenByIDRequest) As WoRMSWebService.getAphiaChildrenByIDResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaID", WrapperNamespace:="http://aphia/v1.0/AphiaID", IsWrapped:=true)>  _
    Partial Public Class getAphiaIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public scientificname As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public marine_only As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal scientificname As String, ByVal marine_only As Boolean)
            MyBase.New
            Me.scientificname = scientificname
            Me.marine_only = marine_only
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaID", IsWrapped:=true)>  _
    Partial Public Class getAphiaIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://aphia/v1.0")>  _
    Partial Public Class AphiaRecord
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private aphiaIDField As Integer
        
        Private urlField As String
        
        Private scientificnameField As String
        
        Private authorityField As String
        
        Private rankField As String
        
        Private statusField As String
        
        Private valid_AphiaIDField As Integer
        
        Private valid_nameField As String
        
        Private valid_authorityField As String
        
        Private kingdomField As String
        
        Private phylumField As String
        
        Private classField As String
        
        Private orderField As String
        
        Private familyField As String
        
        Private genusField As String
        
        Private citationField As String
        
        Private lsidField As String
        
        '''<remarks/>
        Public Property AphiaID() As Integer
            Get
                Return Me.aphiaIDField
            End Get
            Set
                Me.aphiaIDField = value
                Me.RaisePropertyChanged("AphiaID")
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
                Me.RaisePropertyChanged("url")
            End Set
        End Property
        
        '''<remarks/>
        Public Property scientificname() As String
            Get
                Return Me.scientificnameField
            End Get
            Set
                Me.scientificnameField = value
                Me.RaisePropertyChanged("scientificname")
            End Set
        End Property
        
        '''<remarks/>
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
                Me.RaisePropertyChanged("authority")
            End Set
        End Property
        
        '''<remarks/>
        Public Property rank() As String
            Get
                Return Me.rankField
            End Get
            Set
                Me.rankField = value
                Me.RaisePropertyChanged("rank")
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        Public Property valid_AphiaID() As Integer
            Get
                Return Me.valid_AphiaIDField
            End Get
            Set
                Me.valid_AphiaIDField = value
                Me.RaisePropertyChanged("valid_AphiaID")
            End Set
        End Property
        
        '''<remarks/>
        Public Property valid_name() As String
            Get
                Return Me.valid_nameField
            End Get
            Set
                Me.valid_nameField = value
                Me.RaisePropertyChanged("valid_name")
            End Set
        End Property
        
        '''<remarks/>
        Public Property valid_authority() As String
            Get
                Return Me.valid_authorityField
            End Get
            Set
                Me.valid_authorityField = value
                Me.RaisePropertyChanged("valid_authority")
            End Set
        End Property
        
        '''<remarks/>
        Public Property kingdom() As String
            Get
                Return Me.kingdomField
            End Get
            Set
                Me.kingdomField = value
                Me.RaisePropertyChanged("kingdom")
            End Set
        End Property
        
        '''<remarks/>
        Public Property phylum() As String
            Get
                Return Me.phylumField
            End Get
            Set
                Me.phylumField = value
                Me.RaisePropertyChanged("phylum")
            End Set
        End Property
        
        '''<remarks/>
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
                Me.RaisePropertyChanged("class")
            End Set
        End Property
        
        '''<remarks/>
        Public Property order() As String
            Get
                Return Me.orderField
            End Get
            Set
                Me.orderField = value
                Me.RaisePropertyChanged("order")
            End Set
        End Property
        
        '''<remarks/>
        Public Property family() As String
            Get
                Return Me.familyField
            End Get
            Set
                Me.familyField = value
                Me.RaisePropertyChanged("family")
            End Set
        End Property
        
        '''<remarks/>
        Public Property genus() As String
            Get
                Return Me.genusField
            End Get
            Set
                Me.genusField = value
                Me.RaisePropertyChanged("genus")
            End Set
        End Property
        
        '''<remarks/>
        Public Property citation() As String
            Get
                Return Me.citationField
            End Get
            Set
                Me.citationField = value
                Me.RaisePropertyChanged("citation")
            End Set
        End Property
        
        '''<remarks/>
        Public Property lsid() As String
            Get
                Return Me.lsidField
            End Get
            Set
                Me.lsidField = value
                Me.RaisePropertyChanged("lsid")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://aphia/v1.0")>  _
    Partial Public Class Vernacular
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private vernacularField As String
        
        Private language_codeField As String
        
        Private languageField As String
        
        '''<remarks/>
        Public Property vernacular() As String
            Get
                Return Me.vernacularField
            End Get
            Set
                Me.vernacularField = value
                Me.RaisePropertyChanged("vernacular")
            End Set
        End Property
        
        '''<remarks/>
        Public Property language_code() As String
            Get
                Return Me.language_codeField
            End Get
            Set
                Me.language_codeField = value
                Me.RaisePropertyChanged("language_code")
            End Set
        End Property
        
        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
                Me.RaisePropertyChanged("language")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://aphia/v1.0")>  _
    Partial Public Class Source
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private source_idField As Integer
        
        Private useField As String
        
        Private referenceField As String
        
        Private pageField As String
        
        Private urlField As String
        
        Private linkField As String
        
        Private fulltextField As String
        
        '''<remarks/>
        Public Property source_id() As Integer
            Get
                Return Me.source_idField
            End Get
            Set
                Me.source_idField = value
                Me.RaisePropertyChanged("source_id")
            End Set
        End Property
        
        '''<remarks/>
        Public Property use() As String
            Get
                Return Me.useField
            End Get
            Set
                Me.useField = value
                Me.RaisePropertyChanged("use")
            End Set
        End Property
        
        '''<remarks/>
        Public Property reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("reference")
            End Set
        End Property
        
        '''<remarks/>
        Public Property page() As String
            Get
                Return Me.pageField
            End Get
            Set
                Me.pageField = value
                Me.RaisePropertyChanged("page")
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
                Me.RaisePropertyChanged("url")
            End Set
        End Property
        
        '''<remarks/>
        Public Property link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
                Me.RaisePropertyChanged("link")
            End Set
        End Property
        
        '''<remarks/>
        Public Property fulltext() As String
            Get
                Return Me.fulltextField
            End Get
            Set
                Me.fulltextField = value
                Me.RaisePropertyChanged("fulltext")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://aphia/v1.0")>  _
    Partial Public Class Classification
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private aphiaIDField As Integer
        
        Private rankField As String
        
        Private scientificnameField As String
        
        Private childField As Classification
        
        '''<remarks/>
        Public Property AphiaID() As Integer
            Get
                Return Me.aphiaIDField
            End Get
            Set
                Me.aphiaIDField = value
                Me.RaisePropertyChanged("AphiaID")
            End Set
        End Property
        
        '''<remarks/>
        Public Property rank() As String
            Get
                Return Me.rankField
            End Get
            Set
                Me.rankField = value
                Me.RaisePropertyChanged("rank")
            End Set
        End Property
        
        '''<remarks/>
        Public Property scientificname() As String
            Get
                Return Me.scientificnameField
            End Get
            Set
                Me.scientificnameField = value
                Me.RaisePropertyChanged("scientificname")
            End Set
        End Property
        
        '''<remarks/>
        Public Property child() As Classification
            Get
                Return Me.childField
            End Get
            Set
                Me.childField = value
                Me.RaisePropertyChanged("child")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecords", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public scientificname As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public [like] As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public fuzzy As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public marine_only As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public offset As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal scientificname As String, ByVal [like] As Boolean, ByVal fuzzy As Boolean, ByVal marine_only As Boolean, ByVal offset As Integer)
            MyBase.New
            Me.scientificname = scientificname
            Me.[like] = [like]
            Me.fuzzy = fuzzy
            Me.marine_only = marine_only
            Me.offset = offset
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordsResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaNameByID", WrapperNamespace:="http://aphia/v1.0/AphiaName", IsWrapped:=true)>  _
    Partial Public Class getAphiaNameByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaNameByIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaName", IsWrapped:=true)>  _
    Partial Public Class getAphiaNameByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordByID", WrapperNamespace:="http://aphia/v1.0/AphiaRecord", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordByIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecord", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordByTSN", WrapperNamespace:="http://aphia/v1.0/AphiaRecord", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordByTSNRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public TSN As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TSN As Integer)
            MyBase.New
            Me.TSN = TSN
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordByTSNResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecord", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordByTSNResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordsByNames", WrapperNamespace:="http://aphia/v1.0/AphiaMatches", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsByNamesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public scientificnames() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public [like] As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public fuzzy As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public marine_only As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal scientificnames() As String, ByVal [like] As Boolean, ByVal fuzzy As Boolean, ByVal marine_only As Boolean)
            MyBase.New
            Me.scientificnames = scientificnames
            Me.[like] = [like]
            Me.fuzzy = fuzzy
            Me.marine_only = marine_only
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordsByNamesResponse", WrapperNamespace:="http://aphia/v1.0/AphiaMatches", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsByNamesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]()() As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]()() As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordsByVernacular", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsByVernacularRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public vernacular As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public [like] As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public offset As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vernacular As String, ByVal [like] As Boolean, ByVal offset As Integer)
            MyBase.New
            Me.vernacular = vernacular
            Me.[like] = [like]
            Me.offset = offset
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaRecordsByVernacularResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaRecordsByVernacularResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaClassificationByID", WrapperNamespace:="http://aphia/v1.0/Classification", IsWrapped:=true)>  _
    Partial Public Class getAphiaClassificationByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaClassificationByIDResponse", WrapperNamespace:="http://aphia/v1.0/Classification", IsWrapped:=true)>  _
    Partial Public Class getAphiaClassificationByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return] As WoRMSWebService.Classification
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As WoRMSWebService.Classification)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getSourcesByAphiaID", WrapperNamespace:="http://aphia/v1.0/Sources", IsWrapped:=true)>  _
    Partial Public Class getSourcesByAphiaIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getSourcesByAphiaIDResponse", WrapperNamespace:="http://aphia/v1.0/Sources", IsWrapped:=true)>  _
    Partial Public Class getSourcesByAphiaIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.Source
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.Source)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaSynonymsByID", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaSynonymsByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaSynonymsByIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaSynonymsByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaVernacularsByID", WrapperNamespace:="http://aphia/v1.0/AphiaVernaculars", IsWrapped:=true)>  _
    Partial Public Class getAphiaVernacularsByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaVernacularsByIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaVernaculars", IsWrapped:=true)>  _
    Partial Public Class getAphiaVernacularsByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.Vernacular
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.Vernacular)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaChildrenByID", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaChildrenByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public AphiaID As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public offset As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AphiaID As Integer, ByVal offset As Integer)
            MyBase.New
            Me.AphiaID = AphiaID
            Me.offset = offset
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getAphiaChildrenByIDResponse", WrapperNamespace:="http://aphia/v1.0/AphiaRecords", IsWrapped:=true)>  _
    Partial Public Class getAphiaChildrenByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public [return]() As WoRMSWebService.AphiaRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As WoRMSWebService.AphiaRecord)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AphiaNameServicePortTypeChannel
        Inherits WoRMSWebService.AphiaNameServicePortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AphiaNameServicePortTypeClient
        Inherits System.ServiceModel.ClientBase(Of WoRMSWebService.AphiaNameServicePortType)
        Implements WoRMSWebService.AphiaNameServicePortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaID(ByVal request As WoRMSWebService.getAphiaIDRequest) As WoRMSWebService.getAphiaIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaID
            Return MyBase.Channel.getAphiaID(request)
        End Function
        
        Public Function getAphiaID(ByVal scientificname As String, ByVal marine_only As Boolean) As Integer
            Dim inValue As WoRMSWebService.getAphiaIDRequest = New WoRMSWebService.getAphiaIDRequest()
            inValue.scientificname = scientificname
            inValue.marine_only = marine_only
            Dim retVal As WoRMSWebService.getAphiaIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaRecords(ByVal request As WoRMSWebService.getAphiaRecordsRequest) As WoRMSWebService.getAphiaRecordsResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaRecords
            Return MyBase.Channel.getAphiaRecords(request)
        End Function
        
        Public Function getAphiaRecords(ByVal scientificname As String, ByVal [like] As Boolean, ByVal fuzzy As Boolean, ByVal marine_only As Boolean, ByVal offset As Integer) As WoRMSWebService.AphiaRecord()
            Dim inValue As WoRMSWebService.getAphiaRecordsRequest = New WoRMSWebService.getAphiaRecordsRequest()
            inValue.scientificname = scientificname
            inValue.[like] = [like]
            inValue.fuzzy = fuzzy
            inValue.marine_only = marine_only
            inValue.offset = offset
            Dim retVal As WoRMSWebService.getAphiaRecordsResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaRecords(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaNameByID(ByVal request As WoRMSWebService.getAphiaNameByIDRequest) As WoRMSWebService.getAphiaNameByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaNameByID
            Return MyBase.Channel.getAphiaNameByID(request)
        End Function
        
        Public Function getAphiaNameByID(ByVal AphiaID As Integer) As String
            Dim inValue As WoRMSWebService.getAphiaNameByIDRequest = New WoRMSWebService.getAphiaNameByIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getAphiaNameByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaNameByID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaRecordByID(ByVal request As WoRMSWebService.getAphiaRecordByIDRequest) As WoRMSWebService.getAphiaRecordByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaRecordByID
            Return MyBase.Channel.getAphiaRecordByID(request)
        End Function
        
        Public Function getAphiaRecordByID(ByVal AphiaID As Integer) As WoRMSWebService.AphiaRecord
            Dim inValue As WoRMSWebService.getAphiaRecordByIDRequest = New WoRMSWebService.getAphiaRecordByIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getAphiaRecordByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaRecordByID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaRecordByTSN(ByVal request As WoRMSWebService.getAphiaRecordByTSNRequest) As WoRMSWebService.getAphiaRecordByTSNResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaRecordByTSN
            Return MyBase.Channel.getAphiaRecordByTSN(request)
        End Function
        
        Public Function getAphiaRecordByTSN(ByVal TSN As Integer) As WoRMSWebService.AphiaRecord
            Dim inValue As WoRMSWebService.getAphiaRecordByTSNRequest = New WoRMSWebService.getAphiaRecordByTSNRequest()
            inValue.TSN = TSN
            Dim retVal As WoRMSWebService.getAphiaRecordByTSNResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaRecordByTSN(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaRecordsByNames(ByVal request As WoRMSWebService.getAphiaRecordsByNamesRequest) As WoRMSWebService.getAphiaRecordsByNamesResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaRecordsByNames
            Return MyBase.Channel.getAphiaRecordsByNames(request)
        End Function
        
        Public Function getAphiaRecordsByNames(ByVal scientificnames() As String, ByVal [like] As Boolean, ByVal fuzzy As Boolean, ByVal marine_only As Boolean) As WoRMSWebService.AphiaRecord()()
            Dim inValue As WoRMSWebService.getAphiaRecordsByNamesRequest = New WoRMSWebService.getAphiaRecordsByNamesRequest()
            inValue.scientificnames = scientificnames
            inValue.[like] = [like]
            inValue.fuzzy = fuzzy
            inValue.marine_only = marine_only
            Dim retVal As WoRMSWebService.getAphiaRecordsByNamesResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaRecordsByNames(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaRecordsByVernacular(ByVal request As WoRMSWebService.getAphiaRecordsByVernacularRequest) As WoRMSWebService.getAphiaRecordsByVernacularResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaRecordsByVernacular
            Return MyBase.Channel.getAphiaRecordsByVernacular(request)
        End Function
        
        Public Function getAphiaRecordsByVernacular(ByVal vernacular As String, ByVal [like] As Boolean, ByVal offset As Integer) As WoRMSWebService.AphiaRecord()
            Dim inValue As WoRMSWebService.getAphiaRecordsByVernacularRequest = New WoRMSWebService.getAphiaRecordsByVernacularRequest()
            inValue.vernacular = vernacular
            inValue.[like] = [like]
            inValue.offset = offset
            Dim retVal As WoRMSWebService.getAphiaRecordsByVernacularResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaRecordsByVernacular(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaClassificationByID(ByVal request As WoRMSWebService.getAphiaClassificationByIDRequest) As WoRMSWebService.getAphiaClassificationByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaClassificationByID
            Return MyBase.Channel.getAphiaClassificationByID(request)
        End Function
        
        Public Function getAphiaClassificationByID(ByVal AphiaID As Integer) As WoRMSWebService.Classification
            Dim inValue As WoRMSWebService.getAphiaClassificationByIDRequest = New WoRMSWebService.getAphiaClassificationByIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getAphiaClassificationByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaClassificationByID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getSourcesByAphiaID(ByVal request As WoRMSWebService.getSourcesByAphiaIDRequest) As WoRMSWebService.getSourcesByAphiaIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getSourcesByAphiaID
            Return MyBase.Channel.getSourcesByAphiaID(request)
        End Function
        
        Public Function getSourcesByAphiaID(ByVal AphiaID As Integer) As WoRMSWebService.Source()
            Dim inValue As WoRMSWebService.getSourcesByAphiaIDRequest = New WoRMSWebService.getSourcesByAphiaIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getSourcesByAphiaIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getSourcesByAphiaID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaSynonymsByID(ByVal request As WoRMSWebService.getAphiaSynonymsByIDRequest) As WoRMSWebService.getAphiaSynonymsByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaSynonymsByID
            Return MyBase.Channel.getAphiaSynonymsByID(request)
        End Function
        
        Public Function getAphiaSynonymsByID(ByVal AphiaID As Integer) As WoRMSWebService.AphiaRecord()
            Dim inValue As WoRMSWebService.getAphiaSynonymsByIDRequest = New WoRMSWebService.getAphiaSynonymsByIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getAphiaSynonymsByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaSynonymsByID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaVernacularsByID(ByVal request As WoRMSWebService.getAphiaVernacularsByIDRequest) As WoRMSWebService.getAphiaVernacularsByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaVernacularsByID
            Return MyBase.Channel.getAphiaVernacularsByID(request)
        End Function
        
        Public Function getAphiaVernacularsByID(ByVal AphiaID As Integer) As WoRMSWebService.Vernacular()
            Dim inValue As WoRMSWebService.getAphiaVernacularsByIDRequest = New WoRMSWebService.getAphiaVernacularsByIDRequest()
            inValue.AphiaID = AphiaID
            Dim retVal As WoRMSWebService.getAphiaVernacularsByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaVernacularsByID(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WoRMSWebService_AphiaNameServicePortType_getAphiaChildrenByID(ByVal request As WoRMSWebService.getAphiaChildrenByIDRequest) As WoRMSWebService.getAphiaChildrenByIDResponse Implements WoRMSWebService.AphiaNameServicePortType.getAphiaChildrenByID
            Return MyBase.Channel.getAphiaChildrenByID(request)
        End Function
        
        Public Function getAphiaChildrenByID(ByVal AphiaID As Integer, ByVal offset As Integer) As WoRMSWebService.AphiaRecord()
            Dim inValue As WoRMSWebService.getAphiaChildrenByIDRequest = New WoRMSWebService.getAphiaChildrenByIDRequest()
            inValue.AphiaID = AphiaID
            inValue.offset = offset
            Dim retVal As WoRMSWebService.getAphiaChildrenByIDResponse = CType(Me,WoRMSWebService.AphiaNameServicePortType).getAphiaChildrenByID(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
